import { before, after, it } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { getAuth } from 'firebase-admin/auth';
import { getFirestore } from 'firebase-admin/firestore';
import type { Server } from 'node:http';
import { loadOnboarding } from '../server/onboarding';
let server: Server, base: string;
const club = `onboard-${randomUUID()}`, otherClub = `onboard-other-${randomUUID()}`;
const people: Record<string, { uid: string; token: string; id: number }> = {};
const db = () => getFirestore();
async function person(name: string, role: string, clubId: string, id: number, extras: any = {}) {
 const email = `${name}-${randomUUID()}@example.test`, password = 'Local-onboard-test-2026!'; const account = await getAuth().createUser({ email, password });
 await db().doc(`users/${account.uid}`).set({ id, role, clubId, name, firebaseUid: account.uid, createdAt: new Date().toISOString(), ...extras });
 const r = await fetch(`http://${process.env.FIREBASE_AUTH_EMULATOR_HOST}/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=local-emulator`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password, returnSecureToken: true }) }); assert.equal(r.status, 200); people[name] = { uid: account.uid, id, token: (await r.json()).idToken };
}
async function api(path = '/api/onboarding', name?: string, method = 'GET', body?: any) { const r = await fetch(base + path, { method, headers: { 'Content-Type': 'application/json', ...(name ? { Authorization: `Bearer ${people[name].token}` } : {}) }, ...(body !== undefined ? { body: JSON.stringify(body) } : {}) }); return { status: r.status, body: await r.json() }; }
before(async () => {
 if (!process.env.FIRESTORE_EMULATOR_HOST || !process.env.FIREBASE_AUTH_EMULATOR_HOST) throw Error('Emulators required'); process.env.NODE_ENV = 'production'; process.env.VERCEL = '1'; const { default: app } = await import('../server.ts'); server = app.listen(0, '127.0.0.1'); await new Promise<void>(r => server.once('listening', r)); base = `http://127.0.0.1:${(server.address() as any).port}`;
 for (const [i, name, role] of [[1,'owner','owner'],[2,'manager','manager'],[3,'coach','coach'],[4,'coachB','coach'],[5,'member','member'],[6,'memberB','member'],[7,'superadmin','superadmin']] as const) await person(name, role, club, 8100+i);
 await person('other','owner',otherClub,8200); await db().doc(`clubs/${club}`).set({ accountType:'studio', ownerId:people.owner.uid, isActive:true }); await db().doc(`clubs/${otherClub}`).set({ accountType:'solo', ownerId:people.other.uid, isActive:true });
 await db().doc(`users/${people.member.uid}`).update({ assignedCoachUid:people.coach.uid }); await db().doc(`users/${people.memberB.uid}`).update({ assignedCoachUid:people.coachB.uid });
});
after(async () => { if (server) await new Promise<void>((r,j) => server.close(e => e ? j(e) : r())); });
it('Onboarding bearer required; Member/Superadmin cannot read staff pipeline', async () => { assert.equal((await api()).status,401); for (const name of ['member','superadmin']) assert.equal((await api('/api/onboarding',name)).status,403); const r = await fetch(base+'/api/onboarding',{headers:{Authorization:'Bearer forged'}}); assert.equal(r.status,401); });
it('Owner/Manager Studio all clients, Coach assigned only, foreign and other-coach detail denied; GET read-only', async () => { const before=(await db().doc(`users/${people.member.uid}`).get()).data(); for (const [name,count] of [['owner',2],['manager',2],['coach',1]] as const) { const r=await api('/api/onboarding',name); assert.equal(r.status,200); assert.equal(r.body.total,count); if(name==='coach') { assert.equal(r.body.assessments[0].memberUid,people.member.uid); assert.deepEqual(r.body.coaches,[]); } } for(const name of ['coach','other']) assert.equal((await api(`/api/onboarding/${people.memberB.uid}`,name)).status,404); assert.deepEqual((await db().doc(`users/${people.member.uid}`).get()).data(),before); });
it('Authenticated Solo Owner implicit; Manager Solo denied', async () => { await db().doc(`clubs/${club}`).update({accountType:'solo'}); const r=await api(`/api/onboarding/${people.member.uid}`,'owner'); assert.equal(r.status,200); assert.equal(r.body.assessment.steps.find((s:any)=>s.id==='coach_reference').implicit,true); assert.equal((await api('/api/onboarding','manager')).status,403); await db().doc(`clubs/${club}`).update({accountType:'studio'}); });
it('Staff suspension, club deactivation and owner mismatch reread', async () => { await db().doc(`users/${people.coach.uid}`).update({isSuspended:true}); assert.equal((await api('/api/onboarding','coach')).status,403); await db().doc(`users/${people.coach.uid}`).update({isSuspended:false}); await db().doc(`clubs/${club}`).update({isActive:false}); assert.equal((await api('/api/onboarding','owner')).status,403); await db().doc(`clubs/${club}`).update({isActive:true,ownerId:'different'}); assert.equal((await api('/api/onboarding','owner')).status,403); await db().doc(`clubs/${club}`).update({ownerId:people.owner.uid}); });
it('Bounded pagination/filter cursor tied to actor and facts; forged filters rejected', async () => { const r=await api('/api/onboarding?limit=1','owner'); assert.ok(r.body.nextCursor); const next=await api(`/api/onboarding?limit=1&cursor=${r.body.nextCursor}`,'owner'); assert.notEqual(next.body.assessments[0].memberUid,r.body.assessments[0].memberUid); assert.equal((await api(`/api/onboarding?limit=1&cursor=${r.body.nextCursor}`,'manager')).status,409); assert.equal((await api(`/api/onboarding?coach=${people.coach.uid}`,'owner')).body.total,1); assert.equal((await api(`/api/onboarding?coach=${people.coach.uid}`,'coach')).status,403); for(const q of ['limit=51','state=forged','cursor=bad','search[x]=1','clubId=other']) assert.equal((await api(`/api/onboarding?${q}`,'owner')).status,400); });
const templateId=`${club}-initial`, templateBody={name:'Initial',description:'',questions:[{id:'goal',label:'Votre objectif',type:'text',required:true}],active:true,createdBy:''};
it('Only Owner/Manager configure minimal policy; no template creates BLOCKED; foreign/inactive template and forged authority refused', async () => { for(const name of ['coach','member','superadmin']) assert.equal((await api('/api/onboarding/policy',name,'PUT',{requireInitialAssessment:true})).status,403); assert.equal((await api('/api/onboarding/policy','manager','PUT',{requireInitialAssessment:true})).status,200); let detail=await api(`/api/onboarding/${people.member.uid}`,'owner'); assert.equal(detail.body.assessment.steps.find((s:any)=>s.id==='initial_assessment').state,'blocked'); for(const field of ['clubId','actorUid','role','arbitraryComplete']) assert.equal((await api('/api/onboarding/policy','owner','PUT',{requireInitialAssessment:true,[field]:'forged'})).status,400); await db().doc(`coachCheckInTemplates/${templateId}`).set({...templateBody,clubId:otherClub,createdBy:people.coach.uid}); assert.equal((await api('/api/onboarding/policy','manager','PUT',{requireInitialAssessment:true,initialAssessmentTemplateId:templateId})).status,400); await db().doc(`coachCheckInTemplates/${templateId}`).update({clubId:club}); assert.equal((await api('/api/onboarding/policy','manager','PUT',{requireInitialAssessment:true,initialAssessmentTemplateId:templateId})).status,200); });
it('Existing assignment purpose is validated against policy; matching member response alone completes initial assessment', async () => { const payload={templateId,frequency:{kind:'once'},startDate:new Date().toISOString().slice(0,10),purpose:'onboarding'}; assert.equal((await api(`/api/followup/assignments/${people.memberB.uid}`,'coach','POST',payload)).status,403); assert.equal((await api(`/api/followup/assignments/${people.member.uid}`,'manager','POST',{...payload,purpose:'forged'})).status,400); const assigned=await api(`/api/followup/assignments/${people.member.uid}`,'manager','POST',payload); assert.equal(assigned.status,200); assert.equal(assigned.body.assignment.purpose,'onboarding'); let a=(await api(`/api/onboarding/${people.member.uid}`,'owner')).body.assessment; assert.equal(a.steps.find((s:any)=>s.id==='initial_assessment').state,'pending'); const answered=await api(`/api/followup/checkins/${assigned.body.assignment.id}/respond`,'member','POST',{answers:{goal:'Reprise'}}); assert.equal(answered.status,200); a=(await api(`/api/onboarding/${people.member.uid}`,'owner')).body.assessment; assert.equal(a.steps.find((s:any)=>s.id==='initial_assessment').state,'complete'); });
it('Profile confirmation refuses staff/forged identity/incomplete defaults; validates saved questionnaire, clears only own technical flag', async () => { const path='/api/onboarding/profile-confirmation'; assert.equal((await api(path,'owner','POST')).status,403); assert.equal((await api(path,'member','POST',{memberUid:people.memberB.uid})).status,400); await db().doc(`users/${people.member.uid}`).update({profileMeasurementsPending:true,age:25,weight:70,height:175,trainingDays:3,sessionDuration:60}); assert.equal((await api(path,'member','POST')).status,409); await db().doc(`users/${people.member.uid}`).update({onboardingCompleted:true}); const before=(await db().doc(`users/${people.member.uid}`).get()).data(); assert.equal((await api(path,'member','POST')).status,200); assert.deepEqual((await db().doc(`users/${people.member.uid}`).get()).data(),{...before,profileMeasurementsPending:false}); assert.equal((await api(path,'member','POST')).status,200); });
it('Coach reassignment immediately retracts portfolio/detail', async () => { await db().doc(`users/${people.member.uid}`).update({assignedCoachUid:people.coachB.uid}); assert.equal((await api(`/api/onboarding/${people.member.uid}`,'coach')).status,404); await db().doc(`users/${people.member.uid}`).update({assignedCoachUid:people.coach.uid}); });
for(const count of [0,1,100,500]) it(`Onboarding ${count} members: eight queries + two authority docs for Owner/Manager/Coach, no finance or member-loop`,async()=> { const volume=`${club}-volume-${count}`; await db().doc(`clubs/${volume}`).set({accountType:'studio',isActive:true,ownerId:people.owner.uid}); for(let start=0;start<count;start+=250) { const b=db().batch(); for(let i=start;i<Math.min(count,start+250);i++) b.set(db().doc(`users/${volume}-${i}`),{clubId:volume,role:'member',id:9000+i,name:`Client ${i}`,assignedCoachUid:people.coach.uid,createdAt:new Date().toISOString()}); await b.commit(); } for(const name of ['owner','manager','coach']) { await db().doc(`users/${people[name].uid}`).update({clubId:volume}); let queries=0,docs=0; const wrap=(query:any):any=>new Proxy(query,{get(t,k){if(k==='get')return async()=>{queries++;return t.get();};if(['where','limit'].includes(String(k)))return(...args:any[])=>wrap(t[k](...args));return Reflect.get(t,k,t);}}); const database=new Proxy(db(),{get(t,k){if(k==='collection')return(n:string)=>{assert.ok(!['subscriptions','payments','invoices'].includes(n));return wrap(t.collection(n));};if(k==='doc')return(n:string)=>{assert.ok(!n.startsWith('users/')||n===`users/${people[name].uid}`);const ref=t.doc(n);return new Proxy(ref,{get(r,f){if(f==='get')return async()=>{docs++;return r.get();};const v=Reflect.get(r,f,r);return typeof v==='function'?v.bind(r):v;}});};const v=Reflect.get(t,k,t);return typeof v==='function'?v.bind(t):v;}}); const result=await loadOnboarding(database,people[name].uid); assert.equal(result.assessments.length,count); assert.equal(queries,8);assert.equal(docs,2); await db().doc(`users/${people[name].uid}`).update({clubId:club}); } });
it('Truncated source conservatively marks unknown rather than false completion',async()=> { const wrap=(q:any):any=>new Proxy(q,{get(t,k){if(k==='get')return async()=>({size:10001,docs:Array.from({length:10001},()=>({id:'p',data:()=>({clubId:club,memberId:people.member.id,startDate:'2026-01-01',days:[{exercises:[{exId:1}]}]})}))});if(['where','limit'].includes(String(k)))return(...a:any[])=>wrap(t[k](...a));return Reflect.get(t,k,t);}}); const database=new Proxy(db(),{get(t,k){if(k==='collection')return(n:string)=>n==='programs'?wrap(t.collection(n)):t.collection(n);const v=Reflect.get(t,k,t);return typeof v==='function'?v.bind(t):v;}}); const result=await loadOnboarding(database,people.owner.uid);assert.ok(result.partialSources.includes('programs'));assert.ok(result.assessments.every(a=>a.state==='BLOCKED'&&a.partial&&a.steps.find(s=>s.id==='program_ready')?.state==='unknown')); });

it('Sales conversion appears immediately as derived onboarding with exact prospect UID and no lifecycle/task writes', async () => { const prospectUid=`${club}-converted`; await db().doc(`prospects/${prospectUid}`).set({ id:8300, clubId:club, name:'Nouveau client', phone:'', status:'new', date:new Date().toISOString(), activityHistory:[], notesHistory:[] }); const r=await api(`/api/prospects/${prospectUid}/convert`,'owner','POST',{email:`onboard-converted-${randomUUID()}@example.test`,coachUid:people.coach.uid}); assert.equal(r.status,200); const detail=await api(`/api/onboarding/${r.body.uid}`,'manager'); assert.equal(detail.status,200); assert.equal(detail.body.assessment.state,'IN_PROGRESS'); assert.equal(detail.body.assessment.postSale,true); assert.equal(detail.body.assessment.nextAction.stepId,'profile_completed'); assert.equal((await db().doc(`users/${r.body.uid}`).get()).data()?.sourceProspectUid,prospectUid); assert.equal((await db().collection('tasks').where('clubId','==',club).get()).size,0); assert.equal((await db().collection('onboarding').where('clubId','==',club).get()).size,0); });
