import React, { useState, useRef, useEffect } from 'react';
import type { AppState, Prospect } from '../../types';
import { ProspectSalesDetail, ProspectAssignment, salesRequest } from '../SalesSurface';
import { EmptyState, StatusBadge, ViewTabs } from '../internal/InternalUI';
import { PROSPECT_STAGES, probableProspectDuplicate, prospectStage } from '../prospectCrm';
import { crmDate, prospectTimeline, scopedProspects } from './crmModel';

const questionLabels: Record<string, string> = {
                        age: "Âge", gender: "Sexe", profession: "Profession", condition: "Condition physique", weight: "Poids", height: "Taille", ailments: "Antécédents", medicalTreatments: "Traitements", goals: "Objectifs", obj1: "Objectif n°1", obj2: "Objectif n°2", whenResults: "Résultats attendus", trigger: "Déclic", vision6Months: "Vision dans 6 mois", determination: "Détermination (/10)", supporter: "Soutien", sleep: "Sommeil", stress: "Stress (/10)", water: "Eau (L/J)", habits: "Habitudes (Tabac, Alcool..)", currentSport: "Sport actuel", diet: "Alimentation", dietConstraints: "Contraintes alimentaires", frequency: "Fréquence souhaitée (s/sem)", whenStart: "Date de commencement", availability: "Disponibilités", source: "A connu le club via"
                      };
const answerText = (value: unknown) => Array.isArray(value) ? value.join(', ') : typeof value === 'object' && value ? Object.entries(value).filter(([,v]) => v).map(([key]) => key.replaceAll('-', ' ')).join(', ') : String(value);

export function ProspectRecord({ prospect:p, state, setState, onStage, onReminder, onPlanning }: {
  prospect: Prospect; state: AppState; setState: React.Dispatch<React.SetStateAction<AppState>>;
  onStage: (stage: string) => void; onReminder: () => void; onPlanning: () => void;
}) {
  const [tab,setTab] = useState('overview'), [editing,setEditing] = useState(false), [busy,setBusy] = useState(false), [error,setError] = useState('');
  const [kind,setKind] = useState('note'), [content,setContent] = useState(''), [requestId,setRequestId] = useState(()=>crypto.randomUUID());
  const [draft,setDraft] = useState({name:p.name,firstName:p.firstName||'',lastName:p.lastName||'',email:p.email||'',phone:p.phone||'',source:p.source||'',proposedOffer:p.proposedOffer||'',nextAction:p.nextAction||'',tags:(p.tags||[]).join(', ')});
  const editRef = useRef<HTMLFormElement>(null);
  useEffect(() => { if (editing) editRef.current?.querySelector<HTMLInputElement>('input')?.focus(); }, [editing]);
  const [allowDuplicate,setAllowDuplicate] = useState(false);
  const ownProspects=scopedProspects(state.prospects,state.user,state.currentClub?.id||state.user?.clubId);
  const duplicate=probableProspectDuplicate(ownProspects.filter(v=>v.firebaseUid!==p.firebaseUid),draft.email,draft.phone);
  const merge = (next: Prospect) => setState(prev=>({...prev,prospects:prev.prospects.map(row=>row.firebaseUid===p.firebaseUid?next:row)}));
  const persist = async (path:string,body:unknown) => {setBusy(true);setError('');try {const r=await salesRequest(`/api/sales/prospects/${encodeURIComponent(p.firebaseUid!)}/${path}`,body);merge(r.prospect);return true;}catch(e:any){setError(e.message||'Enregistrement impossible.');return false;}finally{setBusy(false);}};
  const saveProfile = async (event:React.FormEvent) => {event.preventDefault();if(busy||duplicate&&!allowDuplicate)return; if(await persist('profile',{...draft,tags:draft.tags.split(',').map(t=>t.trim()).filter(Boolean)}))setEditing(false);};
  const saveActivity = async (event:React.FormEvent) => {event.preventDefault();if(busy||!content.trim())return;if(await persist('activity',{kind,content,requestId})){setContent('');setRequestId(crypto.randomUUID());}};
  const edit = () => {setDraft({name:p.name,firstName:p.firstName||'',lastName:p.lastName||'',email:p.email||'',phone:p.phone||'',source:p.source||'',proposedOffer:p.proposedOffer||'',nextAction:p.nextAction||'',tags:(p.tags||[]).join(', ')});setEditing(true);setAllowDuplicate(false);};
  const timeline = prospectTimeline(p);
  return <div className="crm-record">
    <div className="vi-actions">{p.phone&&<a className="vi-button" href={`tel:${p.phone}`}>Appeler</a>}{p.email&&<a className="vi-button" href={`mailto:${p.email}`}>Email</a>}<button className="vi-button" onClick={()=>{setTab('notes');setKind('note');}}>Ajouter une note</button>{!p.convertedMemberUid&&p.status!=='won'&&<button className="vi-button vi-button-primary" onClick={onReminder}>Programmer une relance</button>}</div>
    <ViewTabs label="Sections du dossier prospect" items={[["overview","Vue d’ensemble"],["activity","Activité"],["notes","Notes & échanges"],["appointments","Rendez-vous"],["offer","Offre"]]} active={tab} onChange={setTab}/>
    {error&&<p role="alert" className="crm-error">{error}</p>}
    {tab==='overview'&&<>
      <section className="crm-record-card"><header><h3>Informations du contact</h3><button className="vi-button" onClick={edit}>Modifier la fiche</button></header>
      <dl className="crm-facts">{[['Email',p.email],['Téléphone',p.phone],['Prénom',p.firstName],['Nom de famille',p.lastName],['Source',p.source],['Création',crmDate(p.date)],['Dernier contact consigné',p.lastContactAt?crmDate(p.lastContactAt):'Non consigné'],['Responsable',state.currentClub?.accountType==='solo'?state.user?.name:state.users.find(u=>u.clubId===p.clubId&&u.firebaseUid===p.assignedCoachUid)?.name||'Non attribué']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'Non renseigné'}</dd></div>)}</dl><ProspectAssignment prospect={p} state={state} setState={setState}/><div className="crm-card-tags">{(p.tags||[]).map(t=><StatusBadge key={t}>{t}</StatusBadge>)}</div></section>
      <section className="crm-record-card"><h3>Étape et prochaine action</h3><label className="vi-field" htmlFor="crm-stage">Changer d’étape<select id="crm-stage" value={prospectStage(p)} disabled={!!p.convertedMemberUid||p.status==='won'} onChange={e=>onStage(e.target.value)}>{PROSPECT_STAGES.map(s=><option value={s.id} key={s.id}>{s.label}</option>)}</select></label><p>{p.nextAction||'Prochaine action à préciser'} · {p.nextReminderDate?crmDate(p.nextReminderDate):'Sans échéance'}</p>{p.lostReason&&<p>Raison de perte : {p.lostReason}</p>}{p.convertedAt&&<p>Converti le {crmDate(p.convertedAt)}</p>}<div className="vi-actions">{!['won','lost'].includes(p.status)&&<button className="vi-button" onClick={()=>onStage('trial')}>Planifier un essai</button>}{p.nextReminderDate&&!['won','lost'].includes(p.status)&&<button className="vi-button" onClick={()=>onStage('contacted')}>Terminer la relance</button>}{p.status==='lost'&&<button className="vi-button" onClick={()=>onStage('contacted')}>Réouvrir · Contacté</button>}</div></section>
      {!!Object.keys(p.answers||{}).length&&<details className="crm-record-card"><summary>Questionnaire découverte</summary><dl className="crm-facts">{Object.entries(p.answers).filter(([,v])=>v!=null&&v!=='').map(([key,value])=><div key={key}><dt>{questionLabels[key]||key}</dt><dd>{answerText(value)}</dd></div>)}</dl></details>}
    </>}
    {tab==='activity'&&<><p className="crm-muted">Historique conservé : jusqu’à 80 événements et 100 notes. Les activités antérieures absentes ne sont pas reconstituées.</p><ol className="crm-timeline">{timeline.map(a=><li key={a.id}><time>{crmDate(a.date)}</time><div><strong>{a.label}</strong>{a.content&&<p>{a.content}</p>}</div></li>)}</ol></>}
    {tab==='notes'&&<>
      <form className="crm-record-card" onSubmit={saveActivity}><h3>Consigner une activité CRM</h3><p className="crm-muted">Relation commerciale et administrative. Les notes coaching restent dans la fiche client.</p><label className="vi-field">Type<select value={kind} onChange={e=>setKind(e.target.value)} disabled={busy}><option value="note">Note CRM</option><option value="call">Appel effectué</option><option value="email">Email envoyé</option><option value="message">Message envoyé</option></select></label>{kind!=='note'&&<p className="crm-muted">Saisie manuelle d’un échange déjà effectué ; aucun message n’est envoyé par ce formulaire.</p>}<label className="vi-field">{kind==='note'?'Note CRM':'Compte rendu'}<textarea required maxLength={2000} value={content} disabled={busy} onChange={e=>setContent(e.target.value)} /></label><button className="vi-button vi-button-primary" disabled={busy||!content.trim()}>{busy?'Enregistrement…':'Enregistrer l’activité'}</button></form>
      {p.notes&&<section className="crm-record-card"><h3>Note initiale</h3><p className="crm-note">{p.notes}</p></section>}
      {(p.notesHistory||[]).map(n=><section className="crm-record-card" key={n.id}><header><strong>{n.authorName||'Note CRM'}</strong><time>{crmDate(n.date)}</time></header><p className="crm-note">{n.content}</p></section>)}
      {!p.notesHistory?.length&&!p.notes&&<EmptyState title="Aucune note CRM">Gardez ici le contexte de votre relation commerciale.</EmptyState>}
    </>}
    {tab==='appointments'&&<><ProspectSalesDetail showAssignment={false} prospect={p} state={state} setState={setState} onAction={onStage}/><button className="vi-button" onClick={onPlanning}>Ouvrir le planning</button></>}
    {tab==='offer'&&<section className="crm-record-card"><h3>Offre envisagée</h3><p>{p.proposedOffer||'Aucune offre renseignée.'}</p><p className="crm-muted">Une intention commerciale. Aucun abonnement ni paiement n’est déclenché ; la facturation reste gérée dans le dossier membre après conversion.</p><button className="vi-button" onClick={edit}>Renseigner l’offre</button></section>}
    {editing&&<form ref={editRef} className="crm-record-card crm-edit" onSubmit={saveProfile} aria-label="Modifier la fiche CRM"><h3>Modifier la fiche CRM</h3><div className="crm-form-grid">{([['name','Nom affiché',120],['firstName','Prénom',80],['lastName','Nom de famille',80],['email','Email',254],['phone','Téléphone',80],['source','Source',80],['proposedOffer','Offre envisagée',200],['nextAction','Prochaine action',200],['tags','Tags séparés par des virgules',490]] as const).map(([key,label,max])=><label className="vi-field" key={key}>{label}<input name={key} type={key==='email'?'email':'text'} required={key==='name'} maxLength={max} value={draft[key]} disabled={busy} onChange={e=>setDraft(d=>({...d,[key]:e.target.value}))}/></label>)}</div>{duplicate&&<label className="crm-duplicate">Un contact similaire existe déjà : {duplicate.name}.<span><input type="checkbox" checked={allowDuplicate} onChange={e=>setAllowDuplicate(e.target.checked)}/> Conserver explicitement deux contacts distincts</span></label>}<div className="vi-actions"><button className="vi-button vi-button-primary" disabled={busy||!!duplicate&&!allowDuplicate}>Enregistrer la fiche</button><button type="button" className="vi-button" disabled={busy} onClick={()=>setEditing(false)}>Annuler</button></div></form>}
  </div>;
}
