import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';
import { assertTestEmulators } from '../assert-test-emulators.mjs';

const local = {
  GCLOUD_PROJECT: 'demo-velatra',
  FIREBASE_AUTH_EMULATOR_HOST: '127.0.0.1:9099',
  FIRESTORE_EMULATOR_HOST: '127.0.0.1:8080',
  FIREBASE_STORAGE_EMULATOR_HOST: '127.0.0.1:9199'
};
const cliConfig = {
  projectId: 'demo-velatra',
  storageBucket: 'demo-velatra.appspot.com',
  databaseURL: 'https://demo-velatra.firebaseio.com'
};

test('accepts a credential-free demo environment and the config generated by emulators:exec', () => {
  const frozen = Object.freeze({ ...local });
  assert.doesNotThrow(() => assertTestEmulators(frozen));
  assert.doesNotThrow(() => assertTestEmulators({
    ...local, GOOGLE_CLOUD_PROJECT: 'demo-velatra', FIREBASE_SERVICE_ACCOUNT: '',
    FIREBASE_CONFIG: JSON.stringify(cliConfig)
  }));
});

test('refuses absent emulators, remote endpoints and conflicting project selection', () => {
  for (const changes of [
    { GCLOUD_PROJECT: undefined }, { GCLOUD_PROJECT: 'real-project' },
    { GOOGLE_CLOUD_PROJECT: 'real-project' }, { GOOGLE_CLOUD_PROJECT: '' },
    { FIRESTORE_EMULATOR_HOST: undefined },
    { FIREBASE_AUTH_EMULATOR_HOST: 'identitytoolkit.googleapis.com:443' },
    { FIREBASE_STORAGE_EMULATOR_HOST: '127.0.0.1:9198' },
    { FIRESTORE_EMULATOR_HOST: 'https://127.0.0.1:8080' }
  ]) assert.throws(() => assertTestEmulators({ ...local, ...changes }), /Unsafe test environment/);
});

test('refuses credentials inherited from local or cloud tooling without revealing them', () => {
  const secret = 'sentinel-secret-that-must-never-be-printed';
  for (const name of [
    'FIREBASE_SERVICE_ACCOUNT', 'FIREBASE_TOKEN', 'GOOGLE_APPLICATION_CREDENTIALS',
    'google_application_credentials', 'GOOGLE_CREDENTIALS', 'GOOGLE_CLOUD_KEYFILE_JSON',
    'CLOUDSDK_AUTH_ACCESS_TOKEN', 'CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE'
  ]) {
    assert.throws(() => assertTestEmulators({ ...local, [name]: secret }), error =>
      error.message.includes(name) && !error.message.includes(secret));
  }
});

test('refuses file configs, malformed JSON and demo labels pointing at another project', () => {
  for (const config of [
    '/private/credential-config.json', '', '{broken', 'null', '[]', '42',
    JSON.stringify({ projectId: 'real-project' }),
    JSON.stringify({ ...cliConfig, storageBucket: 'real-project.appspot.com' }),
    JSON.stringify({ ...cliConfig, databaseURL: 'https://real-project.firebaseio.com' })
  ]) assert.throws(() => assertTestEmulators({ ...local, FIREBASE_CONFIG: config }), /FIREBASE_CONFIG/);
});

test('CLI fails closed with a nonzero status and prints no supplied sensitive values', () => {
  const script = fileURLToPath(new URL('../assert-test-emulators.mjs', import.meta.url));
  const accepted = spawnSync(process.execPath, [script], { env: local, encoding: 'utf8', timeout: 5000 });
  assert.equal(accepted.status, 0, accepted.stderr);
  assert.match(accepted.stdout, /Test isolation verified/);
  const secret = 'sentinel-do-not-print';
  const rejected = spawnSync(process.execPath, [script], {
    env: { ...local, FIREBASE_TOKEN: secret }, encoding: 'utf8', timeout: 5000
  });
  assert.equal(rejected.status, 1);
  assert.match(rejected.stderr, /FIREBASE_TOKEN/);
  assert.equal((rejected.stdout + rejected.stderr).includes(secret), false);
  assert.equal(rejected.stdout, '');
});
