import React, { useCallback, useEffect, useRef, useState } from 'react';
import { apiFetch } from '../firebase';
import type { Program } from '../types';
import { dayKey, shiftDay, type FollowupQuestion, type JourneyPhase } from '../server/followupModel';

type View = { journey: { phases: JourneyPhase[]; version: number } | null; assignments: any[]; responses: any[]; habits: any[]; entries: any[]; logs: any[]; today: string };
const card = 'rounded-2xl border border-zinc-200 bg-white p-4 sm:p-5 shadow-sm';
const field = 'min-h-11 w-full rounded-xl border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-950 focus:outline-none focus:ring-2 focus:ring-emerald-600';
const action = 'min-h-11 rounded-xl bg-emerald-800 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-900 focus:outline-none focus:ring-2 focus:ring-emerald-600 focus:ring-offset-2 disabled:bg-zinc-200 disabled:text-zinc-700';
const secondary = 'min-h-11 rounded-xl border border-zinc-300 bg-white px-3 py-2 text-sm font-semibold text-zinc-900 hover:bg-zinc-50 focus:outline-none focus:ring-2 focus:ring-emerald-600';
const label = 'block space-y-1 text-sm font-semibold text-zinc-800';

async function request(url: string, method = 'GET', body?: unknown) {
  const response = await apiFetch(url, { method, ...(body ? { headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) } : {}) });
  const result = await response.json();
  if (!response.ok) throw new Error(result.error || 'La demande a échoué.');
  return result;
}

export function CoachFollowup({ memberUid, programs, section }: { memberUid: string; programs: Program[]; section: 'journey' | 'followup' | 'summary' }) {
  const [view, setView] = useState<View | null>(null);
  const requestVersion = useRef(0);
  const [templates, setTemplates] = useState<any[]>([]);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [editing, setEditing] = useState<'phase' | 'template' | 'habit' | 'assign' | null>(null);
  const [editingPhaseId, setEditingPhaseId] = useState<string | null>(null);
  const [phase, setPhase] = useState({ name: '', objective: '', startDate: dayKey(), plannedEndDate: '', durationWeeks: '', programId: '', notes: '', checkInTemplateIds: [] as string[] });
  const [templateName, setTemplateName] = useState('');
  const [templateDescription, setTemplateDescription] = useState('');
  const [renamingTemplateId, setRenamingTemplateId] = useState<string | null>(null);
  const [renameValue, setRenameValue] = useState('');
  const [questions, setQuestions] = useState<FollowupQuestion[]>([{ id: 'question1', label: '', type: 'text', required: true }]);
  const [habit, setHabit] = useState({ name: '', description: '', valueType: 'boolean', target: '', unit: '', startDate: dayKey(), kind: 'daily', intervalWeeks: 2 });
  const [assignment, setAssignment] = useState({ templateId: '', kind: 'weekly', intervalWeeks: 2, startDate: dayKey(), phaseId: '' });
  const refresh = useCallback(async () => {
    const version = ++requestVersion.current;
    if (section === 'summary') {
      const result = await request(`/api/followup/clients/${encodeURIComponent(memberUid)}/summary`);
      if (version === requestVersion.current) setView({ journey: result.journey, assignments: [], responses: [], habits: [], entries: [], logs: [], today: dayKey() });
      return;
    }
    if (section === 'journey') {
      const [result, library] = await Promise.all([request(`/api/followup/clients/${encodeURIComponent(memberUid)}/journey`), request('/api/followup/templates')]);
      if (version === requestVersion.current) { setView({ journey: result.journey, assignments: [], responses: [], habits: [], entries: [], logs: [], today: dayKey() }); setTemplates(library.templates || []); }
      return;
    }
    const [followup, library] = await Promise.all([request(`/api/followup/clients/${encodeURIComponent(memberUid)}`), request('/api/followup/templates')]);
    if (version === requestVersion.current) { setView(followup); setTemplates(library.templates || []); }
  }, [memberUid, section]);
  useEffect(() => { setView(null); setError(''); refresh().catch(cause => setError(cause.message)); return () => { requestVersion.current++; }; }, [refresh]);
  const run = async (work: () => Promise<unknown>) => { setBusy(true); setError(''); try { await work(); await refresh(); setEditing(null); } catch (cause: any) { setError(cause.message); } finally { setBusy(false); } };
  const phases = view?.journey?.phases || [];
  const active = phases.find(item => item.status === 'active');
  const next = phases.find(item => item.status === 'planned');
  const savePhases = (updated: JourneyPhase[]) => run(() => request(`/api/followup/journeys/${encodeURIComponent(memberUid)}`, 'PUT', { phases: updated, expectedVersion: view?.journey?.version || 0 }));
  if (error && !view) return <p role="alert" className={card}>{error} <button className={secondary} onClick={() => { setError(''); refresh().catch(cause => setError(cause.message)); }}>Réessayer</button></p>;
  if (!view) return <p role="status" className={card}>Chargement du suivi…</p>;
  if (section === 'summary') return <div className={card}><h3 className="text-sm font-bold text-zinc-900">Parcours de coaching</h3><p className="mt-2 text-sm text-zinc-800">Phase actuelle : <strong>{active?.name || 'Aucune phase active'}</strong></p><p className="text-sm text-zinc-700">Prochaine étape : {next?.name || 'À définir avec le coach'}</p></div>;
  return <div className={section === 'followup' ? 'space-y-5 xl:grid xl:grid-cols-2 xl:gap-5 xl:space-y-0' : 'space-y-5'} aria-label={section === 'journey' ? 'Parcours de coaching' : 'Bilans et habitudes'}>
    {error && <p role="alert" className="rounded-xl border border-red-300 bg-red-50 p-3 text-sm text-red-900">{error}</p>}
    {section === 'followup' && <div className={`${card} xl:col-span-2`}><h3 className="text-sm font-bold text-zinc-950">À retenir pour ce client</h3><div className="mt-2 flex flex-wrap gap-2 text-sm text-zinc-800"><span className="rounded-lg bg-zinc-100 px-3 py-2">Dernier bilan : {view.responses[0]?.answeredAt?.slice(0, 10) || 'aucun'}</span><span className="rounded-lg bg-zinc-100 px-3 py-2">Bilans en retard : {view.assignments.filter(item => item.status === 'late').length}</span>{view.logs.some(item => item.feedback?.pain) && <span className="rounded-lg bg-amber-50 px-3 py-2 text-amber-950">Douleur signalée dans une séance récente</span>}</div></div>}
    {section === 'journey' ? <section className={card}>
      <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-bold text-zinc-950">Parcours</h3><p className="text-sm text-zinc-700">{phases.length ? `${phases.filter(item => item.status === 'completed').length} phase(s) terminée(s) sur ${phases.length}` : 'Aucun parcours créé.'}</p></div><button className={action} onClick={() => { setEditingPhaseId(null); setPhase({ name: '', objective: '', startDate: dayKey(), plannedEndDate: '', durationWeeks: '', programId: '', notes: '', checkInTemplateIds: [] }); setEditing('phase'); }}>+ Ajouter une phase</button></div>
      {phases.length > 0 && <ol className="mt-4 space-y-2">{phases.map((item, index) => <li key={item.id} className="rounded-xl border border-zinc-200 bg-zinc-50 p-3">
        <div className="flex flex-wrap items-start justify-between gap-3"><div><strong className="text-zinc-950">{index + 1}. {item.name}</strong><span className="ml-2 rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-950">{item.status === 'active' ? 'En cours' : item.status === 'completed' ? 'Terminée' : item.status === 'paused' ? 'En pause' : 'Prévue'}</span><p className="mt-1 text-sm text-zinc-800">{item.objective || 'Objectif à définir'}</p><p className="text-xs text-zinc-700">{item.startDate || 'Début à définir'} → {item.plannedEndDate || 'Fin à définir'}{item.programId ? ` · Programme associé` : ''}</p>{item.notes && <p className="mt-1 text-sm text-zinc-700">{item.notes}</p>}</div><div className="flex flex-wrap gap-2">
          {index > 0 && item.status !== 'completed' && <button className={secondary} disabled={busy} aria-label={`Monter ${item.name}`} onClick={() => { const copy = [...phases]; [copy[index - 1], copy[index]] = [copy[index], copy[index - 1]]; savePhases(copy); }}>↑</button>}
          {index < phases.length - 1 && item.status !== 'completed' && <button className={secondary} disabled={busy} aria-label={`Descendre ${item.name}`} onClick={() => { const copy = [...phases]; [copy[index + 1], copy[index]] = [copy[index], copy[index + 1]]; savePhases(copy); }}>↓</button>}
          {item.status === 'planned' && <button className={secondary} disabled={busy} onClick={() => savePhases(phases.map(phase => ({ ...phase, status: phase.id === item.id ? 'active' : phase.status === 'active' ? 'completed' : phase.status, ...(phase.status === 'active' ? { completedAt: new Date().toISOString() } : {}) })))}>Activer</button>}
          {item.status === 'active' && <button className={secondary} disabled={busy} onClick={() => savePhases(phases.map(phase => phase.id === item.id ? { ...phase, status: 'completed', completedAt: new Date().toISOString() } : phase))}>Terminer</button>}
          {item.status === 'active' && <button className={secondary} disabled={busy} onClick={() => savePhases(phases.map(phase => phase.id === item.id ? { ...phase, status: 'paused' } : phase))}>Mettre en pause</button>}
          {item.status === 'paused' && <button className={secondary} disabled={busy} onClick={() => savePhases(phases.map(phase => ({ ...phase, status: phase.id === item.id ? 'active' : phase.status === 'active' ? 'paused' : phase.status })))}>Reprendre</button>}
          {item.status !== 'completed' && <button className={secondary} disabled={busy} onClick={() => { setEditingPhaseId(item.id); setPhase({ name: item.name, objective: item.objective, startDate: item.startDate || '', plannedEndDate: item.plannedEndDate || '', durationWeeks: item.durationWeeks ? String(item.durationWeeks) : '', programId: item.programId || '', notes: item.notes, checkInTemplateIds: item.checkInTemplateIds }); setEditing('phase'); }}>Modifier</button>}
        </div></div>
      </li>)}</ol>}
      {editing === 'phase' && <form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); const updated: JourneyPhase = { id: editingPhaseId || crypto.randomUUID().replaceAll('-', ''), name: phase.name, objective: phase.objective, durationWeeks: phase.durationWeeks ? Number(phase.durationWeeks) : null, startDate: phase.startDate || null, plannedEndDate: phase.plannedEndDate || null, programId: phase.programId || null, checkInTemplateIds: phase.checkInTemplateIds, notes: phase.notes, status: editingPhaseId ? phases.find(item => item.id === editingPhaseId)!.status : phases.length ? 'planned' : 'active' }; savePhases(editingPhaseId ? phases.map(item => item.id === editingPhaseId ? updated : item) : [...phases, updated]); }}>
        <label className={label}>Nom<input required maxLength={100} className={field} value={phase.name} onChange={event => setPhase({ ...phase, name: event.target.value })} /></label><label className={label}>Objectif<input maxLength={500} className={field} value={phase.objective} onChange={event => setPhase({ ...phase, objective: event.target.value })} /></label>
        <label className={label}>Début<input type="date" className={field} value={phase.startDate} onChange={event => setPhase({ ...phase, startDate: event.target.value })} /></label><label className={label}>Fin prévue<input type="date" className={field} value={phase.plannedEndDate} onChange={event => setPhase({ ...phase, plannedEndDate: event.target.value })} /></label>
        <label className={label}>Durée indicative (semaines)<input type="number" min="1" max="260" className={field} value={phase.durationWeeks} onChange={event => setPhase({ ...phase, durationWeeks: event.target.value })} /></label><label className={label}>Programme associé<select className={field} value={phase.programId} onChange={event => setPhase({ ...phase, programId: event.target.value })}><option value="">Aucun</option>{programs.map(program => <option key={program.id} value={program.id}>{program.name}</option>)}</select></label>
        <label className={`${label} sm:col-span-2`}>Notes<textarea maxLength={2000} className={field} value={phase.notes} onChange={event => setPhase({ ...phase, notes: event.target.value })} /></label><div className="flex gap-2 sm:col-span-2"><button className={action} disabled={busy}>Enregistrer la phase</button><button type="button" className={secondary} onClick={() => setEditing(null)}>Annuler</button></div>
        {templates.length > 0 && <fieldset className="sm:col-span-2"><legend className="text-sm font-semibold text-zinc-800">Bilans associés à cette phase</legend><div className="mt-2 flex flex-wrap gap-3">{templates.map(item => <label key={item.id} className="flex min-h-11 items-center gap-2 text-sm text-zinc-800"><input type="checkbox" checked={phase.checkInTemplateIds.includes(item.id)} onChange={event => setPhase({ ...phase, checkInTemplateIds: event.target.checked ? [...phase.checkInTemplateIds, item.id] : phase.checkInTemplateIds.filter(id => id !== item.id) })} />{item.name}</label>)}</div></fieldset>}
      </form>}
    </section> : <>
      <section className={card}><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-lg font-bold text-zinc-950">Bilans du coach</h3><p className="text-sm text-zinc-700">Questionnaires configurables, distincts du suivi quotidien rapide.</p></div><div className="flex flex-wrap gap-2"><button className={secondary} onClick={() => setEditing('template')}>Créer un modèle</button><button className={action} disabled={!templates.some(item => item.active)} onClick={() => setEditing('assign')}>+ Assigner un bilan</button></div></div>
        {editing === 'template' && <form className="mt-4 space-y-3" onSubmit={event => { event.preventDefault(); run(() => request('/api/followup/templates', 'POST', { name: templateName, description: templateDescription, questions })); }}><label className={label}>Nom du modèle<input required maxLength={100} className={field} value={templateName} onChange={event => setTemplateName(event.target.value)} /></label><label className={label}>Description<input maxLength={500} className={field} value={templateDescription} onChange={event => setTemplateDescription(event.target.value)} /></label>
          {questions.map((question, index) => <div key={question.id} className="rounded-xl border border-zinc-200 bg-zinc-50 p-3 grid gap-2 sm:grid-cols-2"><label className={label}>Question {index + 1}<input required maxLength={180} className={field} value={question.label} onChange={event => setQuestions(questions.map(item => item.id === question.id ? { ...item, label: event.target.value } : item))} /></label><label className={label}>Type<select className={field} value={question.type} onChange={event => setQuestions(questions.map(item => item.id === question.id ? { ...item, type: event.target.value as any, ...(event.target.value === 'number' || event.target.value === 'scale' ? { min: 0, max: 10 } : {}), ...(event.target.value === 'single' || event.target.value === 'multiple' ? { options: ['Oui', 'Non'] } : {}) } : item))}><option value="text">Texte</option><option value="number">Nombre</option><option value="scale">Échelle</option><option value="boolean">Oui / non</option><option value="single">Choix unique</option><option value="multiple">Choix multiple</option></select></label>
            {(question.type === 'single' || question.type === 'multiple') && <label className={label}>Choix (séparés par une virgule)<input className={field} value={question.options?.join(', ') || ''} onChange={event => setQuestions(questions.map(item => item.id === question.id ? { ...item, options: event.target.value.split(',').map(value => value.trim()).filter(Boolean) } : item))} /></label>}
            {(question.type === 'number' || question.type === 'scale') && <div className="flex gap-2"><label className={label}>Min<input type="number" className={field} value={question.min ?? 0} onChange={event => setQuestions(questions.map(item => item.id === question.id ? { ...item, min: Number(event.target.value) } : item))} /></label><label className={label}>Max<input type="number" className={field} value={question.max ?? 10} onChange={event => setQuestions(questions.map(item => item.id === question.id ? { ...item, max: Number(event.target.value) } : item))} /></label></div>}
            <label className="flex min-h-11 items-center gap-2 text-sm text-zinc-800"><input type="checkbox" checked={question.required} onChange={event => setQuestions(questions.map(item => item.id === question.id ? { ...item, required: event.target.checked } : item))} />Obligatoire</label><button type="button" className={secondary} disabled={questions.length === 1} onClick={() => setQuestions(questions.filter(item => item.id !== question.id))}>Retirer</button></div>)}
          <div className="flex flex-wrap gap-2"><button type="button" className={secondary} disabled={questions.length >= 20} onClick={() => setQuestions([...questions, { id: crypto.randomUUID().replaceAll('-', ''), label: '', type: 'text', required: true }])}>+ Question</button><button className={action} disabled={busy}>Enregistrer le modèle</button><button type="button" className={secondary} onClick={() => setEditing(null)}>Annuler</button></div>
        </form>}
        {editing === 'assign' && <form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); run(() => request(`/api/followup/assignments/${encodeURIComponent(memberUid)}`, 'POST', { templateId: assignment.templateId, frequency: { kind: assignment.kind, ...(assignment.kind === 'everyWeeks' ? { intervalWeeks: assignment.intervalWeeks } : {}) }, startDate: assignment.startDate, phaseId: assignment.phaseId || null })); }}><label className={label}>Modèle<select required className={field} value={assignment.templateId} onChange={event => setAssignment({ ...assignment, templateId: event.target.value })}><option value="">Choisir</option>{templates.filter(item => item.active).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className={label}>Fréquence<select className={field} value={assignment.kind} onChange={event => setAssignment({ ...assignment, kind: event.target.value })}><option value="daily">Quotidien</option><option value="weekly">Hebdomadaire</option><option value="everyWeeks">Toutes les X semaines</option><option value="once">Une fois</option><option value="manual">Questionnaire ponctuel</option></select></label>{assignment.kind === 'everyWeeks' && <label className={label}>Intervalle en semaines<input type="number" min="2" max="12" className={field} value={assignment.intervalWeeks} onChange={event => setAssignment({ ...assignment, intervalWeeks: Number(event.target.value) })} /></label>}<label className={label}>Première échéance<input type="date" className={field} value={assignment.startDate} onChange={event => setAssignment({ ...assignment, startDate: event.target.value })} /></label><label className={label}>Phase associée<select className={field} value={assignment.phaseId} onChange={event => setAssignment({ ...assignment, phaseId: event.target.value })}><option value="">Aucune</option>{phases.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="flex items-end gap-2"><button className={action} disabled={busy}>Assigner</button><button type="button" className={secondary} onClick={() => setEditing(null)}>Annuler</button></div></form>}
        <div className="mt-4 space-y-2">{view.assignments.length ? view.assignments.map(item => <div key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-zinc-200 p-3 text-sm"><span><strong>{item.templateName}</strong> · {item.status === 'late' ? 'En retard' : item.status === 'received' ? 'Reçu' : item.status === 'expected' ? 'Attendu' : 'À venir'}{item.dueDate ? ` · ${item.dueDate}` : ''}</span><button className={secondary} disabled={busy} onClick={() => run(() => request(`/api/followup/assignments/${item.id}`, 'PATCH', { active: !item.active }))}>{item.active ? 'Désactiver' : 'Réactiver'}</button></div>) : <p className="text-sm text-zinc-700">Aucun bilan assigné.</p>}</div>
        <details className="mt-4"><summary className="cursor-pointer font-semibold text-zinc-900">Modèles ({templates.length})</summary><div className="mt-2 space-y-2">{templates.map(item => <div className="flex flex-wrap items-center justify-between gap-2 border-b border-zinc-200 py-2 text-sm" key={item.id}><span>{item.name} · {item.questions.length} question(s) · {item.active ? 'Actif' : 'Archivé'}</span><div className="flex flex-wrap gap-2"><button className={secondary} disabled={busy} onClick={() => { setRenamingTemplateId(item.id); setRenameValue(item.name); }}>Renommer</button><button className={secondary} disabled={busy} onClick={() => run(() => request('/api/followup/templates', 'POST', { name: `${item.name} (copie)`, description: item.description, questions: item.questions }))}>Dupliquer</button><button className={secondary} disabled={busy} onClick={() => run(() => request(`/api/followup/templates/${item.id}`, 'PATCH', { active: !item.active }))}>{item.active ? 'Archiver' : 'Réactiver'}</button></div>{renamingTemplateId === item.id && <form className="flex w-full flex-wrap gap-2" onSubmit={event => { event.preventDefault(); run(() => request(`/api/followup/templates/${item.id}`, 'PATCH', { name: renameValue })); setRenamingTemplateId(null); }}><label className="sr-only" htmlFor={`rename-${item.id}`}>Nouveau nom du modèle</label><input id={`rename-${item.id}`} className={`${field} max-w-xs`} required maxLength={100} value={renameValue} onChange={event => setRenameValue(event.target.value)} /><button className={action} disabled={busy}>Enregistrer</button></form>}</div>)}</div></details>
      </section>
      <section className={card}><h3 className="text-lg font-bold text-zinc-950">Derniers bilans</h3>{view.responses.length ? <div className="mt-3 space-y-2">{view.responses.map(item => <details key={item.id} className="rounded-xl border border-zinc-200 p-3"><summary className="cursor-pointer text-sm font-semibold text-zinc-900">{item.templateName} · {item.answeredAt?.slice(0, 10)}</summary><dl className="mt-3 space-y-2 text-sm">{item.questions.map((question: FollowupQuestion) => <div key={question.id}><dt className="font-semibold text-zinc-800">{question.label}</dt><dd className="text-zinc-700">{Array.isArray(item.answers[question.id]) ? item.answers[question.id].join(', ') : String(item.answers[question.id] ?? '—')}</dd></div>)}</dl></details>)}</div> : <p className="mt-2 text-sm text-zinc-700">Aucune réponse reçue.</p>}</section>
      <section className={card}><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-lg font-bold text-zinc-950">Habitudes</h3><button className={action} onClick={() => setEditing('habit')}>+ Ajouter une habitude</button></div>
        {editing === 'habit' && <form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); run(() => request(`/api/followup/habits/${encodeURIComponent(memberUid)}`, 'POST', { ...habit, target: habit.target ? Number(habit.target) : null, frequency: { kind: habit.kind, ...(habit.kind === 'everyWeeks' ? { intervalWeeks: habit.intervalWeeks } : {}) } })); }}><label className={label}>Nom<input required maxLength={100} className={field} value={habit.name} onChange={event => setHabit({ ...habit, name: event.target.value })} /></label><label className={label}>Type<select className={field} value={habit.valueType} onChange={event => setHabit({ ...habit, valueType: event.target.value })}><option value="boolean">Fait / non fait</option><option value="number">Valeur</option></select></label><label className={label}>Objectif chiffré<input type="number" min="0" className={field} value={habit.target} onChange={event => setHabit({ ...habit, target: event.target.value })} /></label><label className={label}>Unité<input maxLength={30} className={field} value={habit.unit} onChange={event => setHabit({ ...habit, unit: event.target.value })} /></label><label className={label}>Début<input type="date" className={field} value={habit.startDate} onChange={event => setHabit({ ...habit, startDate: event.target.value })} /></label><label className={label}>Fréquence<select className={field} value={habit.kind} onChange={event => setHabit({ ...habit, kind: event.target.value })}><option value="daily">Quotidienne</option><option value="weekly">Hebdomadaire</option><option value="everyWeeks">Toutes les X semaines</option><option value="once">Une fois</option></select></label>{habit.kind === 'everyWeeks' && <label className={label}>Intervalle en semaines<input type="number" min="2" max="12" className={field} value={habit.intervalWeeks} onChange={event => setHabit({ ...habit, intervalWeeks: Number(event.target.value) })} /></label>}<label className={label}>Description<input maxLength={500} className={field} value={habit.description} onChange={event => setHabit({ ...habit, description: event.target.value })} /></label><div className="flex gap-2 sm:col-span-2"><button className={action} disabled={busy}>Ajouter</button><button type="button" className={secondary} onClick={() => setEditing(null)}>Annuler</button></div></form>}
        <div className="mt-3 space-y-2">{view.habits.length ? view.habits.map(item => <div key={item.id} className="flex flex-wrap justify-between gap-2 rounded-xl border border-zinc-200 p-3 text-sm"><span><strong>{item.name}</strong> · {item.week.completed}/{item.week.expected} {item.frequency.kind === 'daily' ? 'jours cette semaine' : 'échéance en cours'} {item.target != null ? `· objectif ${item.target} ${item.unit}` : ''}</span><button className={secondary} disabled={busy} onClick={() => run(() => request(`/api/followup/habits/${item.id}`, 'PATCH', { active: !item.active }))}>{item.active ? 'Archiver' : 'Réactiver'}</button></div>) : <p className="text-sm text-zinc-700">Aucune habitude configurée.</p>}</div>
      </section>
      <section className={card}><h3 className="text-lg font-bold text-zinc-950">Ressenti des séances</h3><div className="mt-2 space-y-2">{view.logs.filter(item => item.feedback).length ? view.logs.filter(item => item.feedback).map(item => <p key={item.id} className="border-b border-zinc-200 py-2 text-sm text-zinc-800">{item.date} · {item.dayName} · difficulté {item.rpe}/10 · énergie {item.feedback.energy}/5{item.feedback.pain ? ` · douleur signalée${item.feedback.painArea ? ` (${item.feedback.painArea})` : ''}` : ''}{item.feedback.comment ? ` · ${item.feedback.comment}` : ''}</p>) : <p className="text-sm text-zinc-700">Aucun retour de séance récent.</p>}</div></section>
    </>}
  </div>;
}

export function MemberFollowup() {
  const [view, setView] = useState<View | null>(null), [error, setError] = useState(''), [success, setSuccess] = useState(''), [busy, setBusy] = useState(false);
  const [openId, setOpenId] = useState<string | null>(null), [answers, setAnswers] = useState<Record<string, any>>({}), [value, setValue] = useState<Record<string, string>>({});
  const [sessionFeedback, setSessionFeedback] = useState({ rpe: 5, energy: 3, pain: false, painArea: '', comment: '' });
  const refresh = useCallback(async () => setView(await request('/api/followup/me')), []);
  useEffect(() => { let live = true; request('/api/followup/me').then(result => { if (live) setView(result); }).catch(cause => { if (live) setError(cause.message); }); return () => { live = false; }; }, []);
  const run = async (work: () => Promise<unknown>, confirmation = 'Enregistré auprès de votre coach.') => { setBusy(true); setError(''); setSuccess(''); try { await work(); await refresh(); setOpenId(null); setSuccess(confirmation); } catch (cause: any) { setError(cause.message); } finally { setBusy(false); } };
  if (!view && !error) return <p role="status" className={card}>Chargement de votre suivi…</p>;
  if (!view) return <p role="alert" className={card}>{error} <button className={secondary} onClick={() => refresh().catch(cause => setError(cause.message))}>Réessayer</button></p>;
  const active = view.journey?.phases.find(item => item.status === 'active');
  const due = view.assignments.filter(item => item.active && ['expected', 'late'].includes(item.status));
  const habits = view.habits.filter(item => item.active && item.dueDate && view.today >= item.startDate && (!item.endDate || view.today <= item.endDate));
  const pendingSession = view.logs.find(item => !item.isCoaching && !item.feedback && item.date >= shiftDay(view.today, -7));
  return <section className="space-y-4" aria-label="Mon suivi de coaching">
    {error && <p role="alert" className="rounded-xl border border-red-300 bg-red-50 p-3 text-sm text-red-900">{error}</p>}
    {success && <p role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-950">✓ {success}</p>}
    {active && <div className={card}><p className="text-xs font-bold uppercase tracking-wide text-emerald-900">Ma phase actuelle</p><h3 className="mt-1 text-lg font-bold text-zinc-950">{active.name}</h3><p className="text-sm text-zinc-800">{active.objective}</p>{active.plannedEndDate && <p className="mt-1 text-xs text-zinc-700">Fin prévue le {active.plannedEndDate}</p>}</div>}
    {due.length > 0 && <div className={card}><h3 className="text-lg font-bold text-zinc-950">Votre bilan à remplir</h3>{due.map(item => <div key={item.id} className="mt-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><strong className="text-zinc-950">{item.templateName}</strong><p className="text-xs text-zinc-700">{item.status === 'late' ? 'En retard' : 'Attendu'} · {item.dueDate}</p></div><button className={action} onClick={() => { setOpenId(item.id); setAnswers({}); }}>Remplir maintenant</button></div>
      {openId === item.id && <form className="mt-4 space-y-4" onSubmit={event => { event.preventDefault(); run(() => request(`/api/followup/checkins/${item.id}/respond`, 'POST', { dueDate: item.dueDate, answers }), 'Bilan envoyé à votre coach.'); }}><p className="text-sm text-zinc-700">Vos réponses sont transmises à votre coach.</p>{item.questions.map((question: FollowupQuestion, index: number) => <label key={question.id} className={label}><span>{index + 1}/{item.questions.length} · {question.label}{question.required ? ' *' : ''}</span>{question.type === 'text' ? <textarea required={question.required} maxLength={2000} className={field} value={answers[question.id] || ''} onChange={event => setAnswers({ ...answers, [question.id]: event.target.value })} /> : question.type === 'boolean' || question.type === 'single' ? <select required={question.required} className={field} value={answers[question.id] === undefined ? '' : String(answers[question.id])} onChange={event => setAnswers({ ...answers, [question.id]: question.type === 'boolean' ? event.target.value === 'true' : event.target.value })}><option value="">Choisir</option>{(question.type === 'boolean' ? ['Oui', 'Non'] : question.options || []).map((option: string, i: number) => <option key={option} value={question.type === 'boolean' ? String(i === 0) : option}>{option}</option>)}</select> : question.type === 'multiple' ? <span className="space-y-2">{question.options?.map(option => <span key={option} className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={(answers[question.id] || []).includes(option)} onChange={event => { const values = new Set<string>(answers[question.id] || []); event.target.checked ? values.add(option) : values.delete(option); setAnswers({ ...answers, [question.id]: [...values] }); }} />{option}</span>)}</span> : <input type="number" inputMode="decimal" min={question.min} max={question.max} required={question.required} className={field} value={answers[question.id] ?? ''} onChange={event => setAnswers({ ...answers, [question.id]: event.target.value === '' ? undefined : Number(event.target.value) })} />}</label>)}<div className="flex gap-2"><button className={action} disabled={busy}>Envoyer mon bilan</button><button type="button" className={secondary} onClick={() => setOpenId(null)}>Plus tard</button></div></form>}
    </div>)}</div>}
    {habits.length > 0 && <div className={card}><h3 className="text-lg font-bold text-zinc-950">Mes habitudes aujourd’hui</h3><div className="mt-3 space-y-2">{habits.map(item => <div key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-zinc-200 p-3"><div><strong className="text-sm text-zinc-950">{item.name}</strong><p className="text-xs text-zinc-700">{item.target != null ? `${item.target} ${item.unit || ''}` : item.description}</p></div>{item.todayEntry ? <span className="text-sm font-semibold text-emerald-900">✓ Enregistré{item.valueType === 'number' ? ` · ${item.todayEntry.value} ${item.unit}` : ''}</span> : item.valueType === 'number' ? <div className="flex gap-2"><input aria-label={`Valeur ${item.name}`} type="number" inputMode="decimal" min="0" className={`${field} max-w-24`} value={value[item.id] || ''} onChange={event => setValue({ ...value, [item.id]: event.target.value })} /><button className={action} disabled={busy || !value[item.id]} onClick={() => run(() => request(`/api/followup/habits/${item.id}/complete`, 'POST', { value: Number(value[item.id]) }))}>Valider</button></div> : <button className={action} disabled={busy} onClick={() => run(() => request(`/api/followup/habits/${item.id}/complete`, 'POST', { value: true }))}>✓ Fait</button>}</div>)}</div></div>}
    {pendingSession && <details className={card}><summary className="cursor-pointer text-sm font-semibold text-zinc-950">Donner mon ressenti sur {pendingSession.dayName || 'ma séance'} du {pendingSession.date}</summary><form className="mt-3 space-y-3" onSubmit={event => { event.preventDefault(); run(() => request(`/api/followup/sessions/${pendingSession.id}/feedback`, 'POST', sessionFeedback)); }}><label className={label}>Difficulté : {sessionFeedback.rpe}/10<input type="range" min="1" max="10" value={sessionFeedback.rpe} onChange={event => setSessionFeedback({ ...sessionFeedback, rpe: Number(event.target.value) })} className="w-full accent-emerald-800" /></label><label className={label}>Énergie : {sessionFeedback.energy}/5<input type="range" min="1" max="5" value={sessionFeedback.energy} onChange={event => setSessionFeedback({ ...sessionFeedback, energy: Number(event.target.value) })} className="w-full accent-emerald-800" /></label><label className="flex min-h-11 items-center gap-2 text-sm text-zinc-800"><input type="checkbox" checked={sessionFeedback.pain} onChange={event => setSessionFeedback({ ...sessionFeedback, pain: event.target.checked })} />Douleur ressentie</label>{sessionFeedback.pain && <label className={label}>Zone<input className={field} maxLength={100} value={sessionFeedback.painArea} onChange={event => setSessionFeedback({ ...sessionFeedback, painArea: event.target.value })} /></label>}<label className={label}>Commentaire facultatif<textarea className={field} maxLength={1000} value={sessionFeedback.comment} onChange={event => setSessionFeedback({ ...sessionFeedback, comment: event.target.value })} /></label><button className={action} disabled={busy}>Envoyer mon ressenti</button></form></details>}
  </section>;
}
