import React, { useEffect, useState } from 'react';
import { apiFetch } from '../firebase';
import { Button } from '../components/UI';
import type { Club } from '../types';
import './onboarding.css';
export function OnboardingPolicy({ templates }: { templates: any[] }) {
  const [policy, setPolicy] = useState<NonNullable<NonNullable<Club['settings']>['onboarding']>>({ requireInitialAssessment: false });
  const [error, setError] = useState(''), [ready, setReady] = useState(false), [busy, setBusy] = useState(false), [saved, setSaved] = useState(false);
  useEffect(() => { let live = true; apiFetch('/api/onboarding/policy').then(async r => { const data = await r.json(); if (!r.ok) throw Error(data.error); if (live) { setPolicy(data.policy || { requireInitialAssessment: false }); setReady(true); } }).catch(e => { if (live) setError(e.message); }); return () => { live = false; }; }, []);
  return <details className="va-onboarding rounded-xl border p-4 xl:col-span-2" data-onboarding-policy><summary className="cursor-pointer font-semibold">Politique du bilan initial de cet espace</summary><p className="mt-2 text-sm">Facultatif par défaut. Un bilan obligatoire utilise un modèle de Suivi et nécessite la réponse du membre.</p>{error && <p role="alert">{error}</p>}{saved && <p role="status">Politique enregistrée.</p>}{ready && <form className="mt-3 space-y-3" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); setSaved(false); try { const r = await apiFetch('/api/onboarding/policy', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(policy) }); const data = await r.json(); if (!r.ok) throw Error(data.error); setPolicy(data.policy); setSaved(true); } catch (cause: any) { setError(cause.message); } finally { setBusy(false); } }}><label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={policy.requireInitialAssessment} onChange={e => setPolicy({ ...policy, requireInitialAssessment: e.target.checked })} />Exiger un bilan initial</label><label className="block text-sm">Modèle initial<select value={policy.initialAssessmentTemplateId || ''} onChange={e => setPolicy({ requireInitialAssessment: policy.requireInitialAssessment, ...(e.target.value ? { initialAssessmentTemplateId: e.target.value } : {}) })}><option value="">Aucun modèle configuré</option>{templates.filter(t => t.active).map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label><Button disabled={busy}>Enregistrer la politique</Button></form>}</details>;
}
