// Role/format functional regression using the actual RootApp and scoped Firebase fixtures. It stubs Firebase and never writes to production.
import { build } from 'esbuild';
import puppeteer from 'puppeteer';
import { createServer } from 'node:http';
import { readFile, writeFile, readdir, mkdir, rm } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';
import { tmpdir } from 'node:os';
import assert from 'node:assert/strict';

const root=path.resolve(fileURLToPath(new URL('../..',import.meta.url)));
const work=path.join(tmpdir(),'velatra-onboarding-browser');
const evidence=process.env.VELATRA_ONBOARDING_QA_OUTPUT || path.join(work,'evidence');
await rm(work,{recursive:true,force:true});await mkdir(work,{recursive:true});await mkdir(evidence,{recursive:true});
const imported=new Set(['auth','db','firebaseConfig','googleProvider','apiFetch','getMessagingClient','getStorageClient','onAuthStateChanged','onSnapshot','getDoc','getDocFromServer','getDocs','doc','collection','query','where','signOut','signInWithEmailAndPassword','setDoc','updateDoc','deleteDoc','addDoc','getDownloadURL','uploadBytes','ref','listAll']);
async function scan(dir){for(const ent of await readdir(dir,{withFileTypes:true})){if(ent.name.startsWith('.')||['node_modules','dist'].includes(ent.name))continue;const full=path.join(dir,ent.name);if(ent.isDirectory()){await scan(full);}else if(/\.tsx?$/.test(ent.name)){const source=await readFile(full,'utf8');const ast=ts.createSourceFile(full,source,ts.ScriptTarget.Latest,true);ast.forEachChild(node=>{const moduleName=node.moduleSpecifier?.text;if(moduleName==='../firebase'||moduleName==='../../firebase'||moduleName==='./firebase'||moduleName?.startsWith('firebase/')){const bindings=node.importClause?.namedBindings;if(bindings&&ts.isNamedImports(bindings))for(const item of bindings.elements)imported.add(item.propertyName?.text||item.name.text);}});}}}
await scan(root);
const engineFile=path.join(work,'engine.mjs');
await build({stdin:{contents:`export * from '${root}/onboarding/onboardingEngine.ts';export * from '${root}/onboarding/onboardingPulse.ts';export * from '${root}/pulse/pulseEngine.ts';export * from '${root}/retention/retentionEngine.ts';export * from '${root}/retention/retentionPulse.ts';export {snoozeUntil} from '${root}/pulse/pulseModel.ts';`,resolveDir:root,loader:'ts'},outfile:engineFile,bundle:true,platform:'node',format:'esm'});
const {assessOnboarding,withOnboardingActions,derivePulse,applyPulseStates,snoozeUntil,assessRetention,retentionCounts,withRetentionActions}=await import(engineFile);
const known=`
const params=new URLSearchParams(location.search);const role=params.get('role')||'coach';const uid='context-'+role;window.__qaListeners=[];window.__qaApi=[];window.__qaWrites=[];window.__qaSignouts=0;
const user={uid,email:'fixture@example.test',emailVerified:true,getIdToken:async()=> 'fixture-token'};
const profile={id:10,firebaseUid:uid,clubId:'context-club',name:'Coach Test',role,onboardingCompleted:true,xp:0,assignedMemberIds:[]};
const club={id:'context-club',ownerId:'context-owner',accountType:params.get('accountType')||'studio',name:'Club recette',isActive:true,canAddStaff:true,settings:{booking:{enabled:true,schedule:[],sessionTypes:[{id:'coaching',name:'Coaching',durationMinutes:60}]}}};
if(params.get('memberQuestionnaire'))Object.assign(profile,{role:'member',onboardingCompleted:false,profileMeasurementsPending:true,age:30,weight:70,height:175,objectifs:[]});
export const auth={currentUser:null};export const db={};export const firebaseConfig={projectId:'demo-velatra'};export const googleProvider={};
const coach={id:11,role:'coach',firebaseUid:'context-coach',clubId:club.id,name:'Coach Lucas',onboardingCompleted:true};
const owner={...profile,id:12,role:'owner',firebaseUid:'context-owner',name:'Owner Studio'};
const count=Number(params.get('clients')||1);const members=Array.from({length:count},(_,index)=>({id:901+index,role:'member',firebaseUid:'member-'+index,clubId:club.id,name:index?'Client '+index:'Emma Martin',email:'emma@example.test',assignedCoachUid:'context-coach',status:'active',avatar:'EM',gender:'F',xp:0,streak:0,pointsFidelite:0,createdAt:'2026-09-01',objectifs:[],notes:'',age:30,weight:70,height:175,planRequested:index===0,lastWorkoutDate:new Date(Date.now()-10*86400000).toISOString()}));
const foreign={...members[0],id:9998,firebaseUid:'foreign',clubId:'other',name:'FOREIGN TENANT'};const reassigned={...members[0],id:9999,firebaseUid:'reassigned',assignedCoachUid:'other-coach',name:'OTHER PORTFOLIO'};
const iso=date=>date.toISOString();const day=new Date().toLocaleDateString('en-CA',{timeZone:'Europe/Paris'});
const assignedCoachUid=club.accountType==='solo'?'context-owner':'context-coach';
const data={users:[owner,profile,coach,...members,foreign,reassigned].filter((p,i,all)=>all.findIndex(other=>other.firebaseUid===p.firebaseUid)===i),programs:members.slice(1).map(member=>({id:member.id+1000,clubId:club.id,memberId:member.id,assignedCoachUid,name:'Programme actif',nbDays:1,startDate:iso(new Date(Date.now()-86400000)),durationWeeks:4,days:[{name:'Jour 1',isCoaching:false,exercises:[]}],completedWeeks:[],currentDayIndex:0})),tasks:count?[{id:'task-1',clubId:club.id,title:'Préparer le bilan Emma',description:'Tâche affectée',assignedTo:role==='coach'?'10':'11',relatedMemberId:901,status:'todo',dueDate:day}]:[],bookings:count?[{id:'booking-1',clubId:club.id,coachId:assignedCoachUid,assignedCoachUid,memberId:901,startTime:iso(new Date(Date.now()+5*60000)),endTime:iso(new Date(Date.now()+65*60000)),status:'confirmed',type:'coaching',sessionTypeId:'coaching'}]:[],prospects:count?[{id:500,clubId:club.id,firebaseUid:'prospect-1',name:'Prospect à rappeler',status:'call_pending',nextReminderDate:iso(new Date(Date.now()-86400000)),date:iso(new Date()),activityHistory:[],notesHistory:[]}]:[],messages:count?[{id:600,clubId:club.id,assignedCoachUid:'context-coach',from:901,to:10,text:'Bonjour Coach',date:iso(new Date()),read:false}]:[],subscriptions:count?[{id:'sub-1',clubId:club.id,memberId:901,status:'active',price:100,billingCycle:'monthly',currency:'eur'}]:[],payments:count?[{id:'payment-1',clubId:club.id,memberId:901,status:'paid',amount:100,date:iso(new Date()),currency:'eur'}]:[]};
const pulseStates=[],retentionInterventions=[];const pulseCount='0';
data.users=[owner,profile,coach,...members].filter((p,i,all)=>all.findIndex(other=>other.firebaseUid===p.firebaseUid)===i);
const ago=n=>iso(new Date(Date.now()-n*86400000));
data.logs=[];data.programs=[];data.assignments=[];data.responses=[];data.habits=[];data.entries=[];
members.forEach((member,i)=>{const phase=count===1?2:i%5;member.createdAt=ago(phase===4?1:90);member.planRequested=false;delete member.lastWorkoutDate;if(phase!==4)data.logs.push({id:'log-'+i,clubId:club.id,memberId:member.id,date:ago([1,8,14,21][phase])});data.programs.push({id:'program-'+i,clubId:club.id,memberId:member.id,name:'Programme actif',nbDays:1,completedWeeks:[],currentDayIndex:0,startDate:ago(30),durationWeeks:40,days:[{name:'Jour 1',exercises:[{exerciseId:1}]}]});});
data.tasks=count?[{id:'task-1',clubId:club.id,title:'Appeler Emma — action opérationnelle distincte',assignedTo:String(profile.id),relatedMemberId:901,status:'todo',dueDate:day}]:[];
data.bookings=[];data.prospects=[];data.messages=[];data.payments=[];data.subscriptions=role==='owner'&&count?[{id:'sub-1',clubId:club.id,memberId:901,status:'past_due',price:100,billingCycle:'monthly',currency:'eur'}]:[];

const scenario=params.get('scenario')||'new';const completed=['5','6'].includes(scenario);
club.settings.onboarding={requireInitialAssessment:scenario!=='new',initialAssessmentTemplateId:'initial'};
data.users=[owner,profile,coach,...members].filter((p,i,all)=>all.findIndex(other=>other.firebaseUid===p.firebaseUid)===i);
for(const m of members){m.createdAt=ago(3);m.sourceProspectUid='source-'+m.firebaseUid;m.onboardingCompleted=completed||scenario==='assessment';m.profileMeasurementsPending=!m.onboardingCompleted;if(scenario==='unassigned')delete m.assignedCoachUid;m.planRequested=false;}
data.prospects=members.map(m=>({id:m.id+10000,firebaseUid:m.sourceProspectUid,clubId:club.id,name:m.name,status:'won',convertedMemberUid:m.firebaseUid,convertedAt:ago(3)}));
data.programs=completed?members.map(m=>({id:m.id+1000,clubId:club.id,memberId:m.id,name:'Programme réel',startDate:ago(1),durationWeeks:8,nbDays:1,days:[{name:'Jour 1',isCoaching:false,exercises:[{exId:1,sets:3,reps:'10',rest:'60',tempo:'',duration:'',notes:'',setGroup:null,setType:null,setName:null}]}],completedWeeks:[],currentDayIndex:0})):[];
data.logs=scenario==='6'?members.map(m=>({id:m.id+2000,clubId:club.id,memberId:m.id,date:day,completedAt:ago(0.2),isCoaching:false,dayName:'Jour 1',exerciseData:{'1':'10'}})):[];
data.bookings=scenario==='5'?members.map(m=>({id:'first-'+m.id,clubId:club.id,memberId:m.id,coachId:club.accountType==='solo'?'context-owner':'context-coach',startTime:ago(-1),endTime:ago(-1.04),status:'confirmed',type:'coaching'})):[];
data.templates=scenario==='blocked'?[]:[{id:'initial',clubId:club.id,name:'Bilan initial existant',active:true,questions:[{id:'goal',label:'Votre objectif',type:'text',required:true}]}];
data.assignments=completed?members.map(m=>({id:'initial-'+m.firebaseUid,memberUid:m.firebaseUid,clubId:club.id,templateId:'initial',purpose:'onboarding',active:true,startDate:new Date(ago(1)).toLocaleDateString('en-CA',{timeZone:'Europe/Paris'}),createdAt:ago(1),questions:data.templates[0].questions})):[];
data.responses=completed?members.map(m=>({id:'initial-'+m.firebaseUid+'_'+data.assignments.find(a=>a.memberUid===m.firebaseUid).startDate,assignmentId:'initial-'+m.firebaseUid,memberUid:m.firebaseUid,clubId:club.id,templateId:'initial',dueDate:data.assignments.find(a=>a.memberUid===m.firebaseUid).startDate,answeredAt:ago(.1),answers:{goal:'Reprise'}})):[];
data.partialSources=scenario==='0'?['users','programs','logs','bookings','coachCheckInAssignments']:[];data.tasks=[];data.messages=[];data.subscriptions=[];data.payments=[];data.habits=[];data.entries=[];
window.__qaData=data;window.__qaPatchProfile=()=>{for(const m of members){m.onboardingCompleted=true;m.profileMeasurementsPending=false;}subscriptions.filter(e=>e.r.path==='users').forEach(e=>e.cb(snap(scoped(e.r))));};

const docSnap=value=>({id:String(value.firebaseUid||value.id||'fixture'),data:()=>value});
const snap=value=>({exists:()=>!!value,data:()=>value,id:String(value?.firebaseUid||value?.id||'fixture'),docs:Array.isArray(value)?value.map(docSnap):[],forEach:cb=>{if(Array.isArray(value))value.map(docSnap).forEach(cb);},docChanges:()=>Array.isArray(value)?value.map(item=>({type:'added',doc:docSnap(item)})):[]});
export const doc=(_db,...parts)=>({path:parts.join('/')});export const collection=doc;export const query=(r,...args)=>({...r,args});export const where=(...args)=>args;
const getValue=r=>r.path==='users/'+uid?profile:r.path==='clubs/context-club'?club:r.path==='tasks/task-1'?data.tasks[0]:data[r.path];
const scoped=r=>{const value=getValue(r);return Array.isArray(value)?value.filter(item=>(r.args||[]).every(([field,operator,expected])=>operator==='=='?item[field]===expected:operator==='in'?expected.includes(item[field]):true)):value;};
export const getDoc=async r=>snap(getValue(r));export const getDocFromServer=getDoc;export const getDocs=async r=>snap(scoped(r));
export function onAuthStateChanged(_auth,cb){const timer=setTimeout(()=>{auth.currentUser=user;cb(user);},20);return()=>clearTimeout(timer);}
const subscriptions=[];
export function onSnapshot(r,cb){window.__qaListeners.push({path:r.path,args:r.args});const entry={r,cb};subscriptions.push(entry);const timer=setTimeout(()=>cb(snap(scoped(r))),20);return()=>{clearTimeout(timer);const i=subscriptions.indexOf(entry);if(i>=0)subscriptions.splice(i,1);};}
export async function signOut(){auth.currentUser=null;window.__qaSignouts++;}export const signInWithEmailAndPassword=async()=>({user});
export async function apiFetch(path,opts){
  window.__qaApi.push({path,method:opts?.method||'GET'});
  if(path==='/api/onboarding/profile-confirmation'&&profile.role==='member'&&opts?.method==='POST'){profile.profileMeasurementsPending=false;window.__qaWrites.push({path:'profile-confirmation'});subscriptions.filter(e=>e.r.path==='users/'+uid).forEach(e=>e.cb(snap(profile)));return new Response(JSON.stringify({success:true}),{status:200});}
  if(path.startsWith('/api/onboarding')||path.startsWith('/api/pulse')||path.startsWith('/api/retention')){
    const response=await fetch('/__qa/pulse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path,method:opts?.method||'GET',body:opts?.body?JSON.parse(opts.body):null,input:{...data,user:profile,currentClub:club},states:pulseStates,interventions:retentionInterventions,followups:data.assignments.filter(a=>!data.responses.some(r=>r.assignmentId===a.id)).map(a=>({id:a.id,memberUid:a.memberUid,templateName:'Bilan initial',dueDate:day}))}),signal:opts?.signal});
    if(path.startsWith('/api/retention')&&opts?.method==='POST'&&response.ok){const result=await response.clone().json();retentionInterventions.push({...result.intervention,memberUid:path.split('/')[3]});window.__qaWrites.push({path:'retentionInterventions'});}
    if(path.startsWith('/api/pulse')&&opts?.method==='POST'&&response.ok){const result=await response.clone().json();const i=pulseStates.findIndex(item=>item.key===result.state.key);if(i>=0)pulseStates.splice(i,1);pulseStates.push(result.state);window.__qaWrites.push({path:'pulseActionStates',state:result.state});}return response;
  }
  if(opts?.method&&opts.method!=='GET')throw Error('Unexpected mutating API');
  const result=path==='/api/coach/assigned-members'?{assignedMemberIds:members.map(item=>item.id)}:path==='/api/followup/priorities'?{priorities:pulseCount===null&&count?[{memberUid:'member-0',memberName:'Emma Martin',templateName:'Bilan',dueDate:day,status:'expected'}]:[],dueCount:0}:path.startsWith('/api/bookings/availability')?{slots:[]}:path.startsWith('/api/followup/clients/')?{journey:null,assignments:[],responses:[],habits:[],entries:[],logs:[],today:day}:path==='/api/followup/me'?{journey:null,assignments:[],responses:[],habits:[],entries:[],logs:[],today:day}:path==='/api/followup/templates'?{templates:data.templates}:{};
  return new Response(JSON.stringify(result),{status:200,headers:{'Content-Type':'application/json'}});
}
export const getMessagingClient=async()=>null;export const getStorageClient=async()=>({});
const denied=()=>{throw new Error('Unexpected fixture write');};export const setDoc=denied,deleteDoc=denied,addDoc=denied,uploadBytes=denied;
export const updateDoc=async(r,patch)=>{if(profile.role==='member'&&r.path==='users/'+uid&&patch.onboardingCompleted===true&&!Object.hasOwn(patch,'profileMeasurementsPending')){Object.assign(profile,patch);window.__qaWrites.push({path:r.path,patch});subscriptions.filter(e=>e.r.path===r.path).forEach(e=>e.cb(snap(profile)));return;}if(r.path!=='messages/600'||Object.keys(patch).join()!=='read')throw Error('Unexpected fixture write');window.__qaWrites.push({path:r.path,patch});data.messages[0].read=patch.read;};
export const runTransaction=async(_db,fn)=>fn({get:async r=>snap(getValue(r)),update:(r,patch)=>{if(r.path!=='tasks/task-1'||Object.keys(patch).join()!=='status')throw Error('Unexpected fixture transaction');Object.assign(data.tasks[0],patch);window.__qaWrites.push({path:r.path,patch});subscriptions.filter(entry=>entry.r.path==='tasks').forEach(entry=>entry.cb(snap(scoped(entry.r))));}});
export const ref=(...args)=>args;export const getDownloadURL=async()=>'about:blank';export const listAll=async()=>({items:[],prefixes:[]});
`;
const defined=new Set([...known.matchAll(/export (?:async )?(?:const|function)\s+(\w+)/g)].map(m=>m[1]));for(const name of ['updateDoc','deleteDoc','addDoc','uploadBytes'])defined.add(name);
const stub=known+[...imported].filter(name=>!defined.has(name)).map(name=>`export const ${name}=(...args)=>({args});`).join('\n');
const entry=path.join(work,'entry.tsx');
await writeFile(entry,`import React from 'react';import{createRoot}from'react-dom/client';import{BrowserRouter}from'react-router-dom';import{HelmetProvider}from'react-helmet-async';import RootApp from '${root}/RootApp';createRoot(document.getElementById('root')).render(<HelmetProvider><BrowserRouter><RootApp/></BrowserRouter></HelmetProvider>);`);
await build({absWorkingDir:root,entryPoints:[entry],outdir:path.join(work,'bundle'),bundle:true,splitting:true,format:'esm',metafile:true,jsx:'automatic',target:'es2022',nodePaths:[path.join(root,'node_modules')],define:{'process.env.NODE_ENV':'"production"','process.env.APP_URL':'""','import.meta.env':'{"DEV":true,"MODE":"test"}'},plugins:[{name:'fixture',setup(b){b.onResolve({filter:/(?:^firebase\/|(?:^|\/)firebase$)/},()=>({path:'firebase-fixture',namespace:'qa'}));b.onLoad({filter:/.*/,namespace:'qa'},()=>({contents:stub,loader:'js'}));b.onLoad({filter:/[\\/]ErrorBoundary\.tsx$/},async args=>({contents:(await readFile(args.path,'utf8')).replace("console.error('Uncaught UI error:',","console.error('Fixture UI error: '+error.message+' '+error.stack,"),loader:'tsx'}));b.onLoad({filter:/[\\/]App\.tsx$/},async args=>{let source=await readFile(args.path,'utf8');const anchor='const [state, setState] = useState<AppState>(INITIAL_STATE);';if(!source.includes(anchor))throw Error('App fixture instrumentation changed');source=source.replace(anchor,anchor+'\n  (window as any).__qaSetState=setState; (window as any).__qaGetState=()=>state;');return{contents:source,loader:'tsx'};});}}]});
const bundle=path.join(work,'bundle');
const outputList=await readdir(bundle);const jsFile=outputList.find(name=>name.endsWith('.js')&&name.startsWith('entry'));const cssFile=outputList.find(name=>name.endsWith('.css'));
if(!jsFile)throw Error('App entry bundle missing');
const tailwind=await readFile(process.env.VELATRA_QA_TAILWIND_PATH||path.join(tmpdir(),'velatra-tailwind-3.4.17.js')).catch(async()=>{const response=await fetch('https://cdn.tailwindcss.com');if(!response.ok)throw Error('Tailwind QA runtime unavailable');return Buffer.from(await response.arrayBuffer());});
const index=await readFile(path.join(root,'index.html'),'utf8');const meta=index.match(/<meta name="viewport"[^>]+>/)?.[0]||'';const base=(index.match(/<style>([\s\S]*?)<\/style>/)?.[1]||'').replace(/@import[^;]+;/g,'');
const html=`<!doctype html><html lang="fr"><head>${meta}<script src="/tailwind.js"></script><style>${base}</style>${cssFile?`<link rel="stylesheet" href="/${cssFile}">`:''}</head><body><div id="root"></div><script type="module" src="/${jsFile}"></script></body></html>`;
const server=createServer(async(req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;
if(pathname==='/__qa/pulse'){
 try{
 const chunks=[];for await(const chunk of req)chunks.push(chunk);const request=JSON.parse(Buffer.concat(chunks).toString());
 const now=new Date(),uid=request.input.user.firebaseUid,clubId=request.input.currentClub.id,url=new URL(request.path,'http://localhost');
 const input=request.input;
 const assessments=assessRetention({actor:input.user,club:input.currentClub,users:input.users,programs:input.programs,logs:input.logs||[],bookings:input.bookings,assignments:input.assignments||[],responses:input.responses||[],habits:input.habits||[],entries:input.entries||[],messages:input.messages,subscriptions:input.subscriptions,partialSources:[]},now);
 const onboarding=assessOnboarding({actor:input.user,club:input.currentClub,users:input.users,programs:input.programs,logs:input.logs||[],bookings:input.bookings,assignments:input.assignments||[],responses:input.responses||[],templates:input.templates||[],prospects:input.prospects,partialSources:input.partialSources||[]},now);
 const derived=withOnboardingActions(withRetentionActions(derivePulse(request.input,request.followups,now),assessments),onboarding,new Set((input.assignments||[]).filter(a=>a.purpose==='onboarding').map(a=>a.id)),{},assessments);let result;
 if(url.pathname.startsWith('/api/onboarding')){const memberUid=url.pathname.split('/')[3];if(memberUid==='policy')result={policy:input.currentClub.settings.onboarding||{requireInitialAssessment:false}};else if(memberUid)result={assessment:onboarding.find(a=>a.memberUid===memberUid)};else{const filtered=onboarding.filter(a=>(url.searchParams.get('state')==='all'||url.searchParams.get('state')==='active'&&a.needsAttention||a.state===url.searchParams.get('state'))&&(!url.searchParams.get('search')||a.memberName.toLowerCase().includes(url.searchParams.get('search').toLowerCase()))&&(['all',null].includes(url.searchParams.get('coach'))||a.assignedCoachUid===url.searchParams.get('coach')));const offset=Number(url.searchParams.get('cursor')||0);result={assessments:filtered.slice(offset,offset+20),total:filtered.length,activeTotal:onboarding.filter(a=>a.needsAttention&&!a.partial).length,coaches:input.user.role==='coach'?[]:[{uid:'context-coach',name:'Coach Lucas'}],partialSources:input.partialSources||[],nextCursor:offset+20<filtered.length?String(offset+20):null};}}else
 if(url.pathname.startsWith('/api/retention')){
  const memberUid=url.pathname.split('/')[3];
  if(request.method==='POST')result={intervention:{id:request.body.requestId,kind:request.body.kind,note:request.body.note||'',actorUid:uid,createdAt:now.toISOString()}};
  else if(memberUid)result={assessment:assessments.find(item=>item.memberUid===memberUid),interventions:request.interventions.filter(item=>item.memberUid===memberUid),interventionsPartial:false};
  else {const filtered=assessments.filter(item=>(['all',null].includes(url.searchParams.get('state'))||item.state===url.searchParams.get('state'))&&(['all',null].includes(url.searchParams.get('signal'))||item.signals.some(s=>s.type===url.searchParams.get('signal')))&&(['all',null].includes(url.searchParams.get('coach'))||item.assignedCoachUid===url.searchParams.get('coach'))&&item.memberName.toLowerCase().includes((url.searchParams.get('search')||'').toLowerCase()));const offset=Number(url.searchParams.get('cursor')||0);result={assessments:filtered.slice(offset,offset+20),total:filtered.length,counts:retentionCounts(assessments),coaches:input.user.role==='coach'?[]:[{uid:'context-coach',name:'Coach Lucas'}],signalTypes:[...new Set(assessments.flatMap(item=>item.signals.map(s=>s.type)))],nextCursor:offset+20<filtered.length?String(offset+20):null,partialSources:[],evaluatedAt:now.toISOString()};}
 }else
 if(request.method==='POST'){
 const key=decodeURIComponent(url.pathname.split('/')[3]),action=derived.find(item=>item.key===key);
 if(!action||action.sourceFingerprint!==request.body.sourceFingerprint)throw Error('Stale fixture action');
 const snoozed=url.pathname.endsWith('/snooze');result={state:{actorUid:uid,clubId,key,sourceFingerprint:action.sourceFingerprint,status:snoozed?'snoozed':'handled',...(snoozed?{snoozedUntil:snoozeUntil(now,request.body.preset)}:{}),createdAt:now.toISOString(),updatedAt:now.toISOString()}};
 }else{
 const filtered=applyPulseStates(derived,request.states,uid,clubId,now).filter(item=>item.state===(url.searchParams.get('status')||'open')&&(['all',null].includes(url.searchParams.get('group'))||item.group===url.searchParams.get('group'))&&(['all',null].includes(url.searchParams.get('category'))||item.category===url.searchParams.get('category')));
 const offset=Number(url.searchParams.get('cursor')||0),limit=Number(url.searchParams.get('limit')||20);
 result={onboardingSummary:onboarding.filter(a=>a.needsAttention&&!a.partial).length,retentionSummary:retentionCounts(assessments),actions:filtered.slice(offset,offset+limit),total:filtered.length,nextCursor:offset+limit<filtered.length?String(offset+limit):null,categories:request.input.user.role==='coach'?['clients','coaching','followup','messages','tasks','planning']:request.input.user.role==='manager'?['clients','coaching','followup','messages','tasks','planning','crm']:['clients','coaching','followup','messages','tasks','planning','crm','business'],partialSources:[],generatedAt:now.toISOString()};
 }
 res.setHeader('Content-Type','application/json');res.end(JSON.stringify(result));
 }catch(error){res.statusCode=500;res.end(JSON.stringify({error:error.message}));}return;
} if(pathname==='/tailwind.js'){res.setHeader('Content-Type','text/javascript');res.end(tailwind);return;}if(pathname.endsWith('.js')||pathname.endsWith('.css')){res.setHeader('Content-Type',pathname.endsWith('.css')?'text/css':'text/javascript');res.end(await readFile(path.join(bundle,path.basename(pathname))));return;}res.setHeader('Content-Type','text/html');res.end(html);});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin=`http://127.0.0.1:${server.address().port}`;const browser=await puppeteer.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
const records=[],errors=[];
const check=(label,passed,details)=>{records.push({label,passed,details});if(!passed)errors.push({label,details});};
const clickText=async(page,text,selector='button')=>{await page.waitForFunction((selector,label)=>[...document.querySelectorAll(selector)].some(button=>button.offsetHeight&&button.textContent?.trim()===label),{},selector,text);const handle=await page.evaluateHandle((selector,label)=>[...document.querySelectorAll(selector)].find(button=>button.offsetHeight&&button.textContent?.trim()===label),selector,text);const button=handle.asElement();assert.ok(button,`Missing action ${text}`);await button.evaluate(element=>element.scrollIntoView({block:'center'}));await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await button.click();await handle.dispose();};
async function open(role,type,width,height,count,scenario='new'){const page=await browser.newPage();page.setDefaultTimeout(15000);page.setDefaultNavigationTimeout(30000);await page.setViewport({width,height,deviceScaleFactor:1});await page.setRequestInterception(true);page.on('request',r=>r.url().startsWith(origin)?void r.continue():void r.abort());page.on('console',message=>{if(message.type()==='error'&&message.text().includes('Fixture UI error'))console.log(message.text());});page.on('pageerror',error=>errors.push({label:'Runtime exception',details:error.message}));await page.goto(`${origin}/dashboard?role=${role}&accountType=${type}&clients=${count}&scenario=${scenario}`,{waitUntil:'domcontentloaded'});await page.waitForSelector('[data-home-retain]');return page;}
async function inspect(page,name,surface){const data=await page.evaluate(surface=>({overflow:document.documentElement.scrollWidth>innerWidth,short:[...document.querySelectorAll(`${surface} button,${surface} select,${surface} input`)].filter(el=>el.offsetHeight&&el.getBoundingClientRect().height<43.9).map(el=>el.textContent),finance:window.__qaListeners.filter(row=>['subscriptions','payments','invoices','plans'].includes(row.path)),writes:window.__qaWrites.length}),surface);check(name+' layout/touch',!data.overflow&&!data.short.length,data);return data;}
const compositions=new Map();
try {
 const roles=[['owner','solo','SOLO_OWNER'],['owner','studio','STUDIO_OWNER'],['manager','studio','STUDIO_MANAGER'],['coach','studio','STUDIO_COACH']];
 const sizes=[[390,844],[820,1180],[1440,900],[1920,1080]];
 const scenarios=process.env.VELATRA_ONBOARDING_QA_SMOKE?['new','0','2','5','6','blocked']:['new','0','2','5','6','blocked'];
 for(const[role,type,label]of(process.env.VELATRA_ONBOARDING_QA_SMOKE?roles.slice(0,1):roles))for(const[width,height]of(process.env.VELATRA_ONBOARDING_QA_SMOKE?sizes.slice(0,1):sizes))for(const scenario of scenarios){
  const page=await open(role,type,width,height,1,scenario),name=`${label}-${width}-${scenario}`;
  check(name+' Home scope',await page.evaluate(scenario=>scenario==='0'||scenario==='6'?!document.querySelector('[data-home-onboarding]'):!!document.querySelector('[data-home-onboarding]'),scenario));
  const roots=await page.$$eval('.va-mobile-nav button',els=>els.length);check(name+' five mobile roots',roots===5,roots);
  await page.evaluate(()=>window.__qaSetState(p=>({...p,page:'onboarding'})));await page.waitForSelector('[data-onboarding-page]');
  await page.select('select[aria-label="État onboarding"]','all');await page.waitForSelector('[data-onboarding-card]');
  const expectedState=scenario==='0'||scenario==='blocked'?'BLOCKED':scenario==='5'?'READY':scenario==='6'?'COMPLETED':'IN_PROGRESS';const expectedCount=scenario==='0'?0:scenario==='2'?2:scenario==='5'?5:scenario==='6'?6:scenario==='blocked'?2:3;
  check(name+' exact derived state',await page.$eval('[data-onboarding-card] [data-onboarding-state]',(el,v)=>el.dataset.onboardingState===v,expectedState));
  check(name+' factual progress',await page.$eval('[data-onboarding-card] [data-onboarding-progress]',(el,v)=>el.textContent===v+'/6',expectedCount));
  await inspect(page,name,'[data-onboarding-page]');check(name+' coach filter scope',await page.evaluate(role=>!!document.querySelector('[aria-label="Coach onboarding"]')===(role!=='coach'&&window.__qaGetState().currentClub.accountType==='studio'),role));
  await clickText(page,scenario==='6'?'Voir le parcours':'Continuer','[data-onboarding-card] button');await page.waitForSelector('[data-onboarding-detail] [data-onboarding-state]');
  check(name+' correct member',await page.evaluate(()=>history.state.usr.onboardingMemberId===901&&document.querySelector('[data-onboarding-member]')?.textContent==='Emma Martin'));check(name+' detail steps',await page.$$eval('[data-onboarding-step]',(els,c)=>els.length===(c==='6'?0:6),scenario));
  await inspect(page,name+' detail','[data-onboarding-detail]');check(name+' read only',await page.evaluate(()=>window.__qaWrites.length===0));
  if(role==='coach'||role==='manager')check(name+' no finance',await page.evaluate(()=>window.__qaListeners.every(l=>!['subscriptions','payments','plans','invoices'].includes(l.path))));
  if(width===390&&['new','5','6','blocked'].includes(scenario)){await page.evaluate(()=>new Promise(resolve=>{let frames=0;const tick=()=>++frames>=35?resolve():requestAnimationFrame(tick);requestAnimationFrame(tick);}));await page.screenshot({path:path.join(evidence,name+'.png')});}await page.close();
 }
 if(!process.env.VELATRA_ONBOARDING_QA_SMOKE) for(const[role,type,label]of roles){
  const page=await open(role,type,390,844,1,'new');await page.evaluate(()=>window.__qaSetState(p=>({...p,page:'onboarding'})));await page.waitForSelector('[data-onboarding-card]');await clickText(page,'Continuer','[data-onboarding-card] button');await page.waitForSelector('[data-onboarding-detail] [data-onboarding-state]');
  await clickText(page,'Contacter le membre','[data-onboarding-detail] button');await page.waitForSelector('.va-member-dossier');check(label+' profile action contact context',await page.evaluate(()=>history.state.usr.client360MemberId===901&&history.state.usr.client360Section==='communication'));
  await page.evaluate(()=>{window.__qaPatchProfile();window.__qaSetState(p=>({...p,page:'home'}));});await page.waitForSelector('[data-home-onboarding]');await page.evaluate(()=>window.__qaSetState(p=>({...p,page:'onboarding'})));await page.waitForSelector('[data-onboarding-card]');await clickText(page,'Continuer','[data-onboarding-card] button');await page.waitForSelector('[data-onboarding-detail]');await page.waitForFunction(()=>document.querySelector('[data-onboarding-detail]')?.textContent.includes('Préparer le programme'));
  await clickText(page,'Préparer le programme','[data-onboarding-detail] button');await page.waitForSelector('.va-member-dossier');check(label+' program correct member/section',await page.evaluate(()=>history.state.usr.client360MemberId===901&&history.state.usr.client360Section==='coaching'));
  await page.close();
  const readyPage=await open(role,type,390,844,1,'5');await readyPage.evaluate(()=>window.__qaSetState(p=>({...p,page:'onboarding'})));await readyPage.waitForSelector('[data-onboarding-card]');await clickText(readyPage,'Continuer','[data-onboarding-card] button');await readyPage.waitForSelector('[data-onboarding-detail] [data-onboarding-state]');await clickText(readyPage,'Voir la séance','[data-onboarding-detail] button');await readyPage.waitForFunction(()=>history.state.usr?.planningMemberId===901);check(label+' planning selected member',await readyPage.evaluate(()=>window.__qaGetState().page==='calendar'&&history.state.usr.planningMemberId===901));await readyPage.close();
 }

 if(!process.env.VELATRA_ONBOARDING_QA_SMOKE)for(const[role,type,label]of roles){
  const page=await open(role,type,390,844,1,'assessment');await page.evaluate(()=>window.__qaSetState(p=>({...p,page:'onboarding'})));await page.waitForSelector('[data-onboarding-card]');await clickText(page,'Continuer','[data-onboarding-card] button');await page.waitForSelector('[data-onboarding-detail] [data-onboarding-state]');await clickText(page,'Ouvrir Suivi','[data-onboarding-detail] button');await page.waitForFunction(()=>history.state.usr?.client360Section==='followup');check(label+' initial Suivi context',await page.evaluate(()=>history.state.usr.client360MemberId===901));await page.waitForFunction(()=>document.body.textContent.includes('Bilans du coach'));check(label+' configuration authority',await page.evaluate(role=>!!document.querySelector('[data-onboarding-policy]')===(role!=='coach'),role));await clickText(page,'+ Assigner un bilan');check(label+' initial purpose existing form',await page.evaluate(()=>[...document.querySelectorAll('label')].some(el=>el.textContent.includes('Bilan initial (modèle configuré'))));check(label+' no completion shortcut',await page.evaluate(()=>![...document.querySelectorAll('button')].some(b=>/marquer.*termin|tout.*termin/i.test(b.textContent))));await page.close();
  if(type==='studio'&&role!=='coach'){const assign=await open(role,type,390,844,1,'unassigned');await assign.evaluate(()=>window.__qaSetState(p=>({...p,page:'onboarding'})));await assign.waitForSelector('[data-onboarding-card]');await clickText(assign,'Continuer','[data-onboarding-card] button');await assign.waitForSelector('[data-onboarding-detail] [data-onboarding-state]');await clickText(assign,'Affecter le coach','[data-onboarding-detail] button');await assign.waitForFunction(()=>document.body.textContent.includes('Coach responsable'));check(label+' opens existing assignment editor',await assign.evaluate(()=>history.state.usr.client360MemberId===901&&history.state.usr.focusCoachAssignment===true));await assign.close();}
 }
 if(!process.env.VELATRA_ONBOARDING_QA_SMOKE)for(const count of [0,100,500]){
  const page=await open('manager','studio',1440,900,count,'new');await page.evaluate(()=>window.__qaSetState(p=>({...p,page:'onboarding'})));await page.waitForSelector('[data-onboarding-page]');await page.waitForFunction(()=>!document.querySelector('[data-onboarding-page]').textContent.includes('Chargement'));check(`volume-${count} bounded`,await page.$$eval('[data-onboarding-card]',(rows,c)=>rows.length===Math.min(c,20),count));check(`volume-${count} no per-member calls`,await page.evaluate(()=>window.__qaApi.every(r=>!/^\/api\/onboarding\/member-/.test(r.path))));
  if(count===500){const before=await page.$$eval('[data-onboarding-card]',rows=>rows.map(r=>r.textContent));await clickText(page,'Voir les clients suivants');await page.waitForFunction(()=>document.querySelectorAll('[data-onboarding-card]').length===40);check('volume-500 distinct page',await page.$$eval('[data-onboarding-card]',(rows,b)=>new Set(rows.map(r=>r.textContent)).size===40&&rows.slice(0,20).every(r=>b.includes(r.textContent)),before));}
  await page.close();
 }

 if(!process.env.VELATRA_ONBOARDING_QA_SMOKE){const page=await browser.newPage();await page.setViewport({width:390,height:844});page.setDefaultTimeout(15000);await page.setRequestInterception(true);page.on('request',r=>r.url().startsWith(origin)?void r.continue():void r.abort());page.on('pageerror',e=>errors.push({label:'Member exception',details:e.message}));await page.goto(origin+'/dashboard?role=member&accountType=solo&clients=0&memberQuestionnaire=1',{waitUntil:'domcontentloaded'});await page.waitForSelector('#onboarding-age');check('Member technical measurements blank',await page.evaluate(()=>['age','weight','height'].every(k=>document.querySelector('#onboarding-'+k).value==='')));await clickText(page,'Continuer');await page.waitForSelector('[role="alert"]');check('Member cannot accept untouched defaults',await page.evaluate(()=>window.__qaWrites.length===0));for(const[field,value]of[['age','29'],['weight','72'],['height','180']])await page.type('#onboarding-'+field,value);await clickText(page,'Continuer');await clickText(page,'Remise en forme');await clickText(page,'Continuer');await clickText(page,'Continuer');await clickText(page,'Terminer mon profil');await page.waitForFunction(()=>window.__qaGetState().user.onboardingCompleted&&window.__qaGetState().user.profileMeasurementsPending===false);check('Member existing questionnaire confirmed',await page.evaluate(()=>window.__qaWrites.length===2&&window.__qaWrites[0].patch.age===29&&window.__qaWrites[0].patch.weight===72&&window.__qaWrites[0].patch.height===180&&!Object.hasOwn(window.__qaWrites[0].patch,'profileMeasurementsPending')));check('Member no staff pipeline',await page.evaluate(()=>!document.body.textContent.includes('Onboarding Center')));await page.close();}
} catch(e){errors.push({label:'Harness',details:e.stack});} finally {await browser.close();await new Promise(r=>server.close(r));}
await writeFile(path.join(evidence,'results.json'),JSON.stringify({checks:records.length,passed:records.filter(r=>r.passed).length,errors,records},null,2));console.log(JSON.stringify({checks:records.length,passed:records.filter(r=>r.passed).length,errors,output:evidence},null,2));if(errors.length)process.exitCode=1;
