// Role/format functional regression using the actual RootApp and scoped Firebase fixtures. It stubs Firebase and never writes to production.
import { build } from 'esbuild';
import puppeteer from 'puppeteer';
import { createServer } from 'node:http';
import { readFile, writeFile, readdir, mkdir, rm } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';
import { tmpdir } from 'node:os';
import assert from 'node:assert/strict';

const root=path.resolve(fileURLToPath(new URL('../..',import.meta.url)));
const work=path.join(tmpdir(),'velatra-sales-browser');
const evidence=process.env.VELATRA_SALES_QA_OUTPUT || path.join(work,'evidence');
await rm(work,{recursive:true,force:true});await mkdir(work,{recursive:true});await mkdir(evidence,{recursive:true});
const imported=new Set(['auth','db','firebaseConfig','googleProvider','apiFetch','getMessagingClient','getStorageClient','onAuthStateChanged','onSnapshot','getDoc','getDocFromServer','getDocs','doc','collection','query','where','signOut','signInWithEmailAndPassword','setDoc','updateDoc','deleteDoc','addDoc','getDownloadURL','uploadBytes','ref','listAll']);
async function scan(dir){for(const ent of await readdir(dir,{withFileTypes:true})){if(ent.name.startsWith('.')||['node_modules','dist'].includes(ent.name))continue;const full=path.join(dir,ent.name);if(ent.isDirectory()){await scan(full);}else if(/\.tsx?$/.test(ent.name)){const source=await readFile(full,'utf8');const ast=ts.createSourceFile(full,source,ts.ScriptTarget.Latest,true);ast.forEachChild(node=>{const moduleName=node.moduleSpecifier?.text;if(moduleName==='../firebase'||moduleName==='../../firebase'||moduleName==='./firebase'||moduleName?.startsWith('firebase/')){const bindings=node.importClause?.namedBindings;if(bindings&&ts.isNamedImports(bindings))for(const item of bindings.elements)imported.add(item.propertyName?.text||item.name.text);}});}}}
await scan(root);
const engineFile=path.join(work,'engine.mjs');
await build({stdin:{contents:`export * from '${root}/sales/salesEngine.ts';export * from '${root}/sales/salesModel.ts';export * from '${root}/sales/salesPulse.ts';export * from '${root}/pulse/pulseEngine.ts';export * from '${root}/retention/retentionEngine.ts';export * from '${root}/retention/retentionPulse.ts';export {snoozeUntil} from '${root}/pulse/pulseModel.ts';`,resolveDir:root,loader:'ts'},outfile:engineFile,bundle:true,platform:'node',format:'esm'});
const {salesOverview,salesJoins,trialGroup,withSalesActions,derivePulse,applyPulseStates,snoozeUntil,assessRetention,retentionCounts,withRetentionActions}=await import(engineFile);
const known=`
const params=new URLSearchParams(location.search);const role=params.get('role')||'coach';const uid='context-'+role;window.__qaListeners=[];window.__qaApi=[];window.__qaWrites=[];window.__qaSignouts=0;
const user={uid,email:'fixture@example.test',emailVerified:true,getIdToken:async()=> 'fixture-token'};
const profile={id:10,firebaseUid:uid,clubId:'context-club',name:'Coach Test',role,onboardingCompleted:true,xp:0,assignedMemberIds:[]};
const club={id:'context-club',ownerId:'context-owner',accountType:params.get('accountType')||'studio',name:'Club recette',isActive:true,canAddStaff:true,settings:{booking:{enabled:true,schedule:[],sessionTypes:[{id:'coaching',name:'Coaching',durationMinutes:60}]}}};
export const auth={currentUser:null};export const db={};export const firebaseConfig={projectId:'demo-velatra'};export const googleProvider={};
const coach={id:11,role:'coach',firebaseUid:'context-coach',clubId:club.id,name:'Coach Lucas',onboardingCompleted:true};
const owner={...profile,id:12,role:'owner',firebaseUid:'context-owner',name:'Owner Studio'};
const count=Number(params.get('clients')||1);const members=Array.from({length:count},(_,index)=>({id:901+index,role:'member',firebaseUid:'member-'+index,clubId:club.id,name:index?'Client '+index:'Emma Martin',email:'emma@example.test',assignedCoachUid:'context-coach',status:'active',avatar:'EM',gender:'F',xp:0,streak:0,pointsFidelite:0,createdAt:'2026-09-01',objectifs:[],notes:'',age:30,weight:70,height:175,planRequested:index===0,lastWorkoutDate:new Date(Date.now()-10*86400000).toISOString()}));
const foreign={...members[0],id:9998,firebaseUid:'foreign',clubId:'other',name:'FOREIGN TENANT'};const reassigned={...members[0],id:9999,firebaseUid:'reassigned',assignedCoachUid:'other-coach',name:'OTHER PORTFOLIO'};
const iso=date=>date.toISOString();const day=new Date().toLocaleDateString('en-CA',{timeZone:'Europe/Paris'});
const assignedCoachUid=club.accountType==='solo'?'context-owner':'context-coach';
const data={users:[owner,profile,coach,...members,foreign,reassigned].filter((p,i,all)=>all.findIndex(other=>other.firebaseUid===p.firebaseUid)===i),programs:members.slice(1).map(member=>({id:member.id+1000,clubId:club.id,memberId:member.id,assignedCoachUid,name:'Programme actif',nbDays:1,startDate:iso(new Date(Date.now()-86400000)),durationWeeks:4,days:[{name:'Jour 1',isCoaching:false,exercises:[]}],completedWeeks:[],currentDayIndex:0})),tasks:count?[{id:'task-1',clubId:club.id,title:'Préparer le bilan Emma',description:'Tâche affectée',assignedTo:role==='coach'?'10':'11',relatedMemberId:901,status:'todo',dueDate:day}]:[],bookings:count?[{id:'booking-1',clubId:club.id,coachId:assignedCoachUid,assignedCoachUid,memberId:901,startTime:iso(new Date(Date.now()+5*60000)),endTime:iso(new Date(Date.now()+65*60000)),status:'confirmed',type:'coaching',sessionTypeId:'coaching'}]:[],prospects:count?[{id:500,clubId:club.id,firebaseUid:'prospect-1',name:'Prospect à rappeler',status:'call_pending',nextReminderDate:iso(new Date(Date.now()-86400000)),date:iso(new Date()),activityHistory:[],notesHistory:[]}]:[],messages:count?[{id:600,clubId:club.id,assignedCoachUid:'context-coach',from:901,to:10,text:'Bonjour Coach',date:iso(new Date()),read:false}]:[],subscriptions:count?[{id:'sub-1',clubId:club.id,memberId:901,status:'active',price:100,billingCycle:'monthly',currency:'eur'}]:[],payments:count?[{id:'payment-1',clubId:club.id,memberId:901,status:'paid',amount:100,date:iso(new Date()),currency:'eur'}]:[]};
const pulseStates=[],retentionInterventions=[];const pulseCount='0';
const ago=n=>iso(new Date(Date.now()-n*86400000));
data.users=[owner,profile,coach,...members].filter((p,i,all)=>all.findIndex(other=>other.firebaseUid===p.firebaseUid)===i);
data.prospects=Array.from({length:count},(_,i)=>({id:500+i,clubId:club.id,firebaseUid:'prospect-'+i,name:i?'Prospect '+i:'Essai Emma',email:'',phone:'',answers:{},source:i%2?'INSTAGRAM':' Instagram ',date:ago(10),status:i%8===6?'lost':i%8===5?'won':'trial',...(i%8===5?{convertedMemberUid:'member-'+i,convertedAt:ago(1)}:{}),...(i%8===6?{lostAt:ago(1)}:{}),activityHistory:[],notesHistory:[]}));
data.salesEvents=data.prospects.filter((_,i)=>i%2===0).map(p=>({clubId:club.id,prospectUid:p.firebaseUid,eventType:'CONTACTED',at:ago(9)}));
const provider=club.accountType==='solo'?'context-owner':'context-coach';const providerId=role==='coach'?'10':club.accountType==='solo'?'10':'11';
data.bookings=data.prospects.flatMap((p,i)=>{const phase=i%8;const booking={id:'trial-'+i,clubId:club.id,prospectUid:p.firebaseUid,prospectId:p.id,coachId:providerId,coachUid:provider,assignedCoachUid:provider,type:'trial',status:phase===4?'cancelled':'confirmed',startTime:phase===1?iso(new Date(Date.now()+86400000)):ago(2),endTime:phase===1?iso(new Date(Date.now()+90000000)):ago(2-1/24),attendanceStatus:phase===2||phase===5?'SHOWED_UP':phase===3||phase===6?'NO_SHOW':phase===4?'CANCELLED':'PENDING'};return phase===7?[{...booking,attendanceStatus:'NO_SHOW',id:booking.id+'-first',startTime:ago(4),endTime:ago(4-1/24)},{...booking,attendanceStatus:'SHOWED_UP'}]:[booking];});
data.logs=[];data.programs=[];data.assignments=[];data.responses=[];data.habits=[];data.entries=[];data.tasks=[];data.messages=[];data.payments=[];data.subscriptions=[];
const docSnap=value=>({id:String(value.firebaseUid||value.id||'fixture'),data:()=>value});
const snap=value=>({exists:()=>!!value,data:()=>value,id:String(value?.firebaseUid||value?.id||'fixture'),docs:Array.isArray(value)?value.map(docSnap):[],forEach:cb=>{if(Array.isArray(value))value.map(docSnap).forEach(cb);},docChanges:()=>Array.isArray(value)?value.map(item=>({type:'added',doc:docSnap(item)})):[]});
export const doc=(_db,...parts)=>({path:parts.join('/')});export const collection=doc;export const query=(r,...args)=>({...r,args});export const where=(...args)=>args;
const getValue=r=>r.path==='users/'+uid?profile:r.path==='clubs/context-club'?club:r.path==='tasks/task-1'?data.tasks[0]:data[r.path];
const scoped=r=>{const value=getValue(r);return Array.isArray(value)?value.filter(item=>(r.args||[]).every(([field,operator,expected])=>operator==='=='?item[field]===expected:operator==='in'?expected.includes(item[field]):true)):value;};
export const getDoc=async r=>snap(getValue(r));export const getDocFromServer=getDoc;export const getDocs=async r=>snap(scoped(r));
export function onAuthStateChanged(_auth,cb){const timer=setTimeout(()=>{auth.currentUser=user;cb(user);},20);return()=>clearTimeout(timer);}
const subscriptions=[];
export function onSnapshot(r,cb){window.__qaListeners.push({path:r.path,args:r.args});const entry={r,cb};subscriptions.push(entry);const timer=setTimeout(()=>cb(snap(scoped(r))),20);return()=>{clearTimeout(timer);const i=subscriptions.indexOf(entry);if(i>=0)subscriptions.splice(i,1);};}
export async function signOut(){auth.currentUser=null;window.__qaSignouts++;}export const signInWithEmailAndPassword=async()=>({user});
export async function apiFetch(path,opts){
  window.__qaApi.push({path,method:opts?.method||'GET'});
  if(path.startsWith('/api/sales')||path.startsWith('/api/bookings/')&&path.endsWith('/attendance')||path.startsWith('/api/pulse')||path.startsWith('/api/retention')){
    const response=await fetch('/__qa/pulse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path,method:opts?.method||'GET',body:opts?.body?JSON.parse(opts.body):null,input:{...data,user:profile,currentClub:club},states:pulseStates,interventions:retentionInterventions,followups:pulseCount===null&&count?[{id:'assignment',memberUid:'member-0',templateName:'Bilan',dueDate:day}]:[]}),signal:opts?.signal});
    if(path.endsWith('/attendance')&&response.ok){const r=await response.clone().json();const i=data.bookings.findIndex(b=>b.id===r.booking.id);if(i>=0)data.bookings[i]=r.booking;window.__qaWrites.push({path:'bookings/'+r.booking.id});subscriptions.filter(e=>e.r.path==='bookings').forEach(e=>e.cb(snap(scoped(e.r))));}
    if(path.startsWith('/api/retention')&&opts?.method==='POST'&&response.ok){const result=await response.clone().json();retentionInterventions.push({...result.intervention,memberUid:path.split('/')[3]});window.__qaWrites.push({path:'retentionInterventions'});}
    if(path.startsWith('/api/pulse')&&opts?.method==='POST'&&response.ok){const result=await response.clone().json();const i=pulseStates.findIndex(item=>item.key===result.state.key);if(i>=0)pulseStates.splice(i,1);pulseStates.push(result.state);window.__qaWrites.push({path:'pulseActionStates',state:result.state});}return response;
  }
  if(opts?.method&&opts.method!=='GET')throw Error('Unexpected mutating API');
  const result=path==='/api/coach/assigned-members'?{assignedMemberIds:members.map(item=>item.id)}:path==='/api/followup/priorities'?{priorities:pulseCount===null&&count?[{memberUid:'member-0',memberName:'Emma Martin',templateName:'Bilan',dueDate:day,status:'expected'}]:[],dueCount:0}:path.startsWith('/api/bookings/availability')?{slots:[]}:path.startsWith('/api/followup/clients/')?{journey:null,assignments:[],responses:[],habits:[],entries:[],logs:[],today:day}:path==='/api/followup/templates'?{templates:[]}:{};
  return new Response(JSON.stringify(result),{status:200,headers:{'Content-Type':'application/json'}});
}
export const getMessagingClient=async()=>null;export const getStorageClient=async()=>({});
const denied=()=>{throw new Error('Unexpected fixture write');};export const setDoc=denied,deleteDoc=denied,addDoc=denied,uploadBytes=denied;
export const updateDoc=async(r,patch)=>{if(r.path!=='messages/600'||Object.keys(patch).join()!=='read')throw Error('Unexpected fixture write');window.__qaWrites.push({path:r.path,patch});data.messages[0].read=patch.read;};
export const runTransaction=async(_db,fn)=>fn({get:async r=>snap(getValue(r)),update:(r,patch)=>{if(r.path!=='tasks/task-1'||Object.keys(patch).join()!=='status')throw Error('Unexpected fixture transaction');Object.assign(data.tasks[0],patch);window.__qaWrites.push({path:r.path,patch});subscriptions.filter(entry=>entry.r.path==='tasks').forEach(entry=>entry.cb(snap(scoped(entry.r))));}});
export const ref=(...args)=>args;export const getDownloadURL=async()=>'about:blank';export const listAll=async()=>({items:[],prefixes:[]});
`;
const defined=new Set([...known.matchAll(/export (?:async )?(?:const|function)\s+(\w+)/g)].map(m=>m[1]));for(const name of ['updateDoc','deleteDoc','addDoc','uploadBytes'])defined.add(name);
const stub=known+[...imported].filter(name=>!defined.has(name)).map(name=>`export const ${name}=(...args)=>({args});`).join('\n');
const entry=path.join(work,'entry.tsx');
await writeFile(entry,`import React from 'react';import{createRoot}from'react-dom/client';import{BrowserRouter}from'react-router-dom';import{HelmetProvider}from'react-helmet-async';import RootApp from '${root}/RootApp';createRoot(document.getElementById('root')).render(<HelmetProvider><BrowserRouter><RootApp/></BrowserRouter></HelmetProvider>);`);
await build({absWorkingDir:root,entryPoints:[entry],outdir:path.join(work,'bundle'),bundle:true,splitting:true,format:'esm',metafile:true,jsx:'automatic',target:'es2022',nodePaths:[path.join(root,'node_modules')],define:{'process.env.NODE_ENV':'"production"','process.env.APP_URL':'""','import.meta.env':'{"DEV":true,"MODE":"test"}'},plugins:[{name:'fixture',setup(b){b.onResolve({filter:/(?:^firebase\/|(?:^|\/)firebase$)/},()=>({path:'firebase-fixture',namespace:'qa'}));b.onLoad({filter:/.*/,namespace:'qa'},()=>({contents:stub,loader:'js'}));b.onLoad({filter:/[\\/]ErrorBoundary\.tsx$/},async args=>({contents:(await readFile(args.path,'utf8')).replace("console.error('Uncaught UI error:',","console.error('Fixture UI error: '+error.message+' '+error.stack,"),loader:'tsx'}));b.onLoad({filter:/[\\/]App\.tsx$/},async args=>{let source=await readFile(args.path,'utf8');const anchor='const [state, setState] = useState<AppState>(INITIAL_STATE);';if(!source.includes(anchor))throw Error('App fixture instrumentation changed');source=source.replace(anchor,anchor+'\n  (window as any).__qaSetState=setState; (window as any).__qaGetState=()=>state;');return{contents:source,loader:'tsx'};});}}]});
const bundle=path.join(work,'bundle');
const outputList=await readdir(bundle);const jsFile=outputList.find(name=>name.endsWith('.js')&&name.startsWith('entry'));const cssFile=outputList.find(name=>name.endsWith('.css'));
if(!jsFile)throw Error('App entry bundle missing');
const tailwind=await readFile(process.env.VELATRA_QA_TAILWIND_PATH||path.join(tmpdir(),'velatra-tailwind-3.4.17.js')).catch(async()=>{const response=await fetch('https://cdn.tailwindcss.com');if(!response.ok)throw Error('Tailwind QA runtime unavailable');return Buffer.from(await response.arrayBuffer());});
const index=await readFile(path.join(root,'index.html'),'utf8');const meta=index.match(/<meta name="viewport"[^>]+>/)?.[0]||'';const base=(index.match(/<style>([\s\S]*?)<\/style>/)?.[1]||'').replace(/@import[^;]+;/g,'');
const html=`<!doctype html><html lang="fr"><head>${meta}<script src="/tailwind.js"></script><style>${base}</style>${cssFile?`<link rel="stylesheet" href="/${cssFile}">`:''}</head><body><div id="root"></div><script type="module" src="/${jsFile}"></script></body></html>`;
const server=createServer(async(req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;
if(pathname==='/__qa/pulse'){
 try{
 const chunks=[];for await(const chunk of req)chunks.push(chunk);const request=JSON.parse(Buffer.concat(chunks).toString());
 const now=new Date(),uid=request.input.user.firebaseUid,clubId=request.input.currentClub.id,url=new URL(request.path,'http://localhost');
 const input=request.input;
 const assessments=assessRetention({actor:input.user,club:input.currentClub,users:input.users,programs:input.programs,logs:input.logs||[],bookings:input.bookings,assignments:input.assignments||[],responses:input.responses||[],habits:input.habits||[],entries:input.entries||[],messages:input.messages,subscriptions:input.subscriptions,partialSources:[]},now);
 const derived=withRetentionActions(withSalesActions(derivePulse(request.input,request.followups,now),request.input,now),assessments);let result;
 const salesInput={clubId,studio:input.currentClub.accountType==='studio',prospects:input.prospects,bookings:input.bookings,events:input.salesEvents||[],coaches:input.users};
 if(url.pathname.startsWith('/api/sales/overview')){if(input.user.role==='coach')throw Error('Sales global forbidden');result=salesOverview(salesInput,url.searchParams.get('from'),url.searchParams.get('to'),now);}
 else if(url.pathname.startsWith('/api/sales/trials')){const joins=salesJoins(salesInput);const rows=input.bookings.filter(b=>input.user.role!=='coach'||b.coachUid===uid).filter(b=>!url.searchParams.get('group')||trialGroup(b,now)===url.searchParams.get('group')).filter(b=>!url.searchParams.get('prospectUid')||joins.prospect(b)?.firebaseUid===url.searchParams.get('prospectUid')).sort((a,b)=>Date.parse(b.startTime)-Date.parse(a.startTime)||a.id.localeCompare(b.id));const detailId=url.pathname.split('/')[4];const offset=Number(url.searchParams.get('offset')||0);result=detailId?{booking:rows.find(b=>b.id===detailId)}:{trials:rows.slice(offset,offset+20).map(b=>({booking:b,group:trialGroup(b,now),prospectUid:joins.prospect(b)?.firebaseUid,prospectName:joins.prospect(b)?.name,coachName:joins.coach(b)?.name||'Non attribué'})),total:rows.length,partial:false};}
 else if(url.pathname.endsWith('/attendance')){const b=input.bookings.find(b=>b.id===url.pathname.split('/')[3]);if(!b||Date.parse(b.startTime)>Date.now())throw Error('Attendance too early');result={booking:{...b,attendanceStatus:request.body.attendanceStatus,attendanceUpdatedAt:now.toISOString()}};}
 else
 if(url.pathname.startsWith('/api/retention')){
  const memberUid=url.pathname.split('/')[3];
  if(request.method==='POST')result={intervention:{id:request.body.requestId,kind:request.body.kind,note:request.body.note||'',actorUid:uid,createdAt:now.toISOString()}};
  else if(memberUid)result={assessment:assessments.find(item=>item.memberUid===memberUid),interventions:request.interventions.filter(item=>item.memberUid===memberUid),interventionsPartial:false};
  else {const filtered=assessments.filter(item=>(['all',null].includes(url.searchParams.get('state'))||item.state===url.searchParams.get('state'))&&(['all',null].includes(url.searchParams.get('signal'))||item.signals.some(s=>s.type===url.searchParams.get('signal')))&&(['all',null].includes(url.searchParams.get('coach'))||item.assignedCoachUid===url.searchParams.get('coach'))&&item.memberName.toLowerCase().includes((url.searchParams.get('search')||'').toLowerCase()));const offset=Number(url.searchParams.get('cursor')||0);result={assessments:filtered.slice(offset,offset+20),total:filtered.length,counts:retentionCounts(assessments),coaches:input.user.role==='coach'?[]:[{uid:'context-coach',name:'Coach Lucas'}],signalTypes:[...new Set(assessments.flatMap(item=>item.signals.map(s=>s.type)))],nextCursor:offset+20<filtered.length?String(offset+20):null,partialSources:[],evaluatedAt:now.toISOString()};}
 }else
 if(request.method==='POST'){
 const key=decodeURIComponent(url.pathname.split('/')[3]),action=derived.find(item=>item.key===key);
 if(!action||action.sourceFingerprint!==request.body.sourceFingerprint)throw Error('Stale fixture action');
 const snoozed=url.pathname.endsWith('/snooze');result={state:{actorUid:uid,clubId,key,sourceFingerprint:action.sourceFingerprint,status:snoozed?'snoozed':'handled',...(snoozed?{snoozedUntil:snoozeUntil(now,request.body.preset)}:{}),createdAt:now.toISOString(),updatedAt:now.toISOString()}};
 }else{
 const filtered=applyPulseStates(derived,request.states,uid,clubId,now).filter(item=>item.state===(url.searchParams.get('status')||'open')&&(['all',null].includes(url.searchParams.get('group'))||item.group===url.searchParams.get('group'))&&(['all',null].includes(url.searchParams.get('category'))||item.category===url.searchParams.get('category')));
 const offset=Number(url.searchParams.get('cursor')||0),limit=Number(url.searchParams.get('limit')||20);
 result={retentionSummary:retentionCounts(assessments),actions:filtered.slice(offset,offset+limit),total:filtered.length,nextCursor:offset+limit<filtered.length?String(offset+limit):null,categories:request.input.user.role==='coach'?['clients','coaching','followup','messages','tasks','planning']:request.input.user.role==='manager'?['clients','coaching','followup','messages','tasks','planning','crm']:['clients','coaching','followup','messages','tasks','planning','crm','business'],partialSources:[],generatedAt:now.toISOString()};
 }
 res.setHeader('Content-Type','application/json');res.end(JSON.stringify(result));
 }catch(error){res.statusCode=500;res.end(JSON.stringify({error:error.message}));}return;
} if(pathname==='/tailwind.js'){res.setHeader('Content-Type','text/javascript');res.end(tailwind);return;}if(pathname.endsWith('.js')||pathname.endsWith('.css')){res.setHeader('Content-Type',pathname.endsWith('.css')?'text/css':'text/javascript');res.end(await readFile(path.join(bundle,path.basename(pathname))));return;}res.setHeader('Content-Type','text/html');res.end(html);});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin=`http://127.0.0.1:${server.address().port}`;const browser=await puppeteer.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
const records=[],errors=[];
const check=(label,passed,details)=>{records.push({label,passed,details});if(!passed)errors.push({label,details});};
const clickText=async(page,text,selector='button')=>{await page.waitForFunction((selector,label)=>[...document.querySelectorAll(selector)].some(button=>button.offsetHeight&&button.textContent?.trim()===label),{},selector,text);const handle=await page.evaluateHandle((selector,label)=>[...document.querySelectorAll(selector)].find(button=>button.offsetHeight&&button.textContent?.trim()===label),selector,text);const button=handle.asElement();assert.ok(button,`Missing action ${text}`);await button.evaluate(element=>element.scrollIntoView({block:'center'}));await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await button.click();await handle.dispose();};
async function open(role,type,width,height,count){const page=await browser.newPage();page.setDefaultTimeout(15000);page.setDefaultNavigationTimeout(30000);await page.setViewport({width,height,deviceScaleFactor:1});await page.setRequestInterception(true);page.on('request',r=>r.url().startsWith(origin)?void r.continue():void r.abort());page.on('console',m=>{if(m.type()==='error'&&m.text().includes('Fixture UI error'))console.log(m.text());});page.on('pageerror',error=>errors.push({label:'Runtime exception',details:error.message}));await page.goto(`${origin}/dashboard?role=${role}&accountType=${type}&clients=${count}`,{waitUntil:'domcontentloaded'});await page.waitForSelector('[data-home-retain]');await page.evaluate(role=>window.__qaSetState(prev=>({...prev,page:role==='coach'?'calendar':'crm_pipeline'})),role);await page.waitForSelector(role==='coach'?'[data-sales-tab="trials"]':'nav[aria-label="Vues CRM"]');return page;}
async function inspect(page,name,surface){const data=await page.evaluate(surface=>({overflow:document.documentElement.scrollWidth>innerWidth,short:[...document.querySelectorAll(`${surface} button,${surface} select,${surface} input`)].filter(el=>el.offsetHeight&&el.getBoundingClientRect().height<43.9).map(el=>({text:el.textContent,height:el.getBoundingClientRect().height,minHeight:getComputedStyle(el).minHeight,root:getComputedStyle(document.documentElement).fontSize})),finance:window.__qaListeners.filter(row=>['subscriptions','payments','invoices','plans'].includes(row.path)),writes:window.__qaWrites.length}),surface);check(name+' layout/touch',!data.overflow&&!data.short.length,data);return data;}
try{
 for(const[role,type,label]of(process.env.VELATRA_SALES_QA_SMOKE?[['owner','solo','Solo']]:[['owner','solo','Solo'],['manager','studio','Manager'],['coach','studio','Coach'],['owner','studio','StudioOwner']]))for(const[width,height]of(process.env.VELATRA_SALES_QA_SMOKE?[[390,844]]:[[390,844],[820,1180],[1440,900],[1920,1080]]))for(const count of(process.env.VELATRA_SALES_QA_SMOKE?[1]:[0,1,100,500])){
  const page=await open(role,type,width,height,count),name=`${label}-${width}-${count}`;
  if(role!=='coach'){await clickText(page,'Performance','nav[aria-label="Vues CRM"] button');await page.waitForSelector('[data-sales-funnel]');await inspect(page,name+' Performance','[data-sales-tab="performance"]');check(name+' exact lead count',await page.$eval('[data-sales-funnel]',(el,n)=>el.children[0].textContent.includes(String(n)),count));check(name+' cohort explanation',await page.$eval('[data-sales-tab="performance"]',el=>el.textContent.includes('Conversions observées à ce jour')));check(name+' team visibility',await page.$eval('[data-sales-tab="performance"]',(el,studio)=>el.textContent.includes('Résultats opérationnels par Coach')===studio,type==='studio'));await clickText(page,'Essais','nav[aria-label="Vues CRM"] button');}
  await page.waitForSelector('[data-sales-tab="trials"]');await page.waitForFunction(()=>!document.querySelector('[data-sales-tab="trials"]').textContent.includes('Chargement Sales'));
  await inspect(page,name+' Trials','[data-sales-tab="trials"]');check(name+' bounded trial list',await page.$$eval('[data-sales-attendance]',rows=>rows.length<=20));
  for(const group of ['À venir','Présents','No-show','Annulés','Présence à renseigner']){await clickText(page,group,'[data-sales-tab="trials"] button');await page.waitForFunction(()=>!document.querySelector('[data-sales-tab="trials"]').textContent.includes('Chargement Sales'));check(name+' group '+group,await page.$eval('[data-sales-tab="trials"]',el=>!el.querySelector('[role="alert"]')));}
  const requests=await page.evaluate(()=>window.__qaApi);if(role==='manager'||role==='coach')check(name+' no finance listeners',(await page.evaluate(()=>window.__qaListeners)).every(r=>!['payments','subscriptions','invoices','plans'].includes(r.path)));if(role==='coach')check(name+' no global overview',requests.every(r=>!r.path.startsWith('/api/sales/overview')));check(name+' reads never write',await page.evaluate(()=>window.__qaWrites.length===0));
  if(count===500){const before=await page.$$eval('[data-sales-attendance]',rows=>rows.map(r=>r.dataset.salesAttendance));await clickText(page,'Page suivante','[data-sales-tab="trials"] button');await page.waitForFunction(()=>document.querySelectorAll('[data-sales-attendance]').length>0&&!document.querySelector('[data-sales-tab="trials"]').textContent.includes('Chargement'));const after=await page.$$eval('[data-sales-attendance]',rows=>rows.map(r=>r.dataset.salesAttendance));check(name+' distinct pagination',after.every(id=>!before.includes(id)));}
  if(width===390&&count===100)await page.screenshot({path:path.join(evidence,name+'.png')});await page.close();
 }
 for(const[role,type]of[['owner','solo'],['manager','studio'],['owner','studio'],['coach','studio']]){
  const page=await open(role,type,390,844,1);if(role!=='coach')await clickText(page,'Essais','nav[aria-label="Vues CRM"] button');await page.waitForSelector('[data-sales-attendance]');
  await clickText(page,'No-show','[data-sales-attendance] button');await page.waitForFunction(()=>document.querySelector('[data-sales-tab="trials"]').textContent.includes('Aucun essai dans cette catégorie'));
  await clickText(page,'No-show','[data-sales-tab="trials"] > div[aria-label] button');await page.waitForSelector('[data-sales-attendance]');await clickText(page,'Présent','[data-sales-attendance] button');await page.waitForSelector('[role="alertdialog"]');check(role+' correction requires confirmation',await page.evaluate(()=>window.__qaWrites.length===1));check(role+' correction focus',await page.evaluate(()=>document.activeElement.textContent==='Confirmer la correction'));await page.keyboard.press('Enter');await page.waitForFunction(()=>window.__qaWrites.length===2);check(role+' explicit correction writes once',true);
  await clickText(page,'Présents','[data-sales-tab="trials"] > div[aria-label] button');await page.waitForSelector('[data-sales-attendance]');check(role+' shows corrected outcome',await page.$eval('[data-sales-attendance]',el=>el.textContent.includes('Présence : Présent')));
  if(role!=='coach'){await clickText(page,'Ouvrir le prospect / relancer');await page.waitForSelector('[data-sales-prospect]');await page.waitForFunction(()=>document.querySelector('[data-sales-prospect]').textContent.includes('Dernier résultat'));check(role+' Prospect360 trial history',await page.$eval('[data-sales-prospect]',el=>el.textContent.includes('Dernier résultat')&&el.textContent.includes('Convertir en adhérent')));}
  await page.close();
 }
 const page=await open('manager','studio',390,844,100);await page.evaluate(()=>window.__qaSetState(prev=>({...prev,page:'pulse'})));await page.waitForSelector('[data-pulse-page]');await page.waitForFunction(()=>document.body.textContent.includes('présence à renseigner'));check('Pulse real Sales missing attendance',await page.evaluate(()=>document.body.textContent.includes('présence à renseigner')));await page.close();
}catch(error){for(const page of await browser.pages())if(page.url().startsWith(origin)){console.log(JSON.stringify(await page.evaluate(()=>({body:document.body.innerText.slice(0,2500),calls:window.__qaApi?.slice(-5)})),null,2));await page.screenshot({path:path.join(evidence,'failure.png')});}errors.push({label:'Scenario',details:error.stack});}
finally{await browser.close();await new Promise(resolve=>server.close(resolve));await writeFile(path.join(evidence,'results.json'),JSON.stringify({checks:records,failures:errors,environment:'RootApp/CRM/Sales/Planning/Pulse; actual shared pure engine; synthetic API; no production; external requests blocked'},null,2));}
console.log(JSON.stringify({checks:records.length,failures:errors.length,evidence,errors},null,2));if(errors.length)process.exitCode=1;
