import { Link } from 'react-router-dom';
import { ArrowRight, CalendarDays, Users, Dumbbell, Sparkles } from 'lucide-react';
import { PublicMeta, PublicHero, FeatureList, ProductCapture, ProductClosing } from '../components/PublicProduct';

const pillars = [
  { icon: CalendarDays, title: 'Application & gestion', text: 'Clients, planning et paiements dans votre espace de travail.', href: '#gestion' },
  { icon: Users, title: 'CRM', text: 'Du premier contact à l’accompagnement, gardez le fil.', href: '#crm' },
  { icon: Dumbbell, title: 'Coaching & suivi', text: 'Séances, progression et échanges autour de chaque adhérent.', href: '#suivi' },
  { icon: Sparkles, title: 'Programmation', text: 'Votre expertise, avec une création manuelle ou assistée par l’IA.', href: '#programmation' },
];

export default function FeaturesPage() {
  return <div className="vp-page">
    <PublicMeta path="/produit" title="Le produit Velatra — Votre activité de coaching réunie" description="Explorez Velatra : gestion des clients, CRM, programmes, suivi, planning, paiements et assistance IA dans une plateforme de coaching." />
    <PublicHero eyebrow="LE PRODUIT VELATRA" title={<>Un seul espace.<br /><em>Tout le fil du coaching.</em></>} description="Du premier échange avec un prospect au suivi d’une séance, retrouvez les outils qui accompagnent votre quotidien de coach." />
    <div className="marketing-container"><ProductCapture /><nav className="vp-pillars" aria-label="Les quatre piliers du produit">{pillars.map(({ icon: Icon, title, text, href }, index) => <a href={href} key={title}><span className="vp-pillar-number">0{index + 1}<Icon size={20} /></span><h2>{title}</h2><p>{text}</p><ArrowRight size={18} /></a>)}</nav>
      <section className="vp-section vp-split" id="gestion"><div><span className="marketing-kicker">01 · APPLICATION & GESTION</span><h2>Une activité organisée.<br /><em>Une journée plus claire.</em></h2><p>Retrouvez vos clients, vos rendez-vous et vos tâches au même endroit. Les espaces coach et adhérent relient la préparation à l’accompagnement.</p></div><div className="vp-panel"><h3>L’essentiel de votre gestion</h3><FeatureList items={['Fiches adhérents et informations de suivi', 'Planning, rendez-vous et réservations', 'Tâches et organisation du quotidien', 'Suivi des paiements, dépenses et factures']} /><p className="vp-note">Les paiements en ligne nécessitent la connexion et la configuration de votre compte Stripe dans Velatra.</p></div></section>
      <section className="vp-section" id="crm"><div className="vp-section-heading"><span className="marketing-kicker">02 · CRM</span><h2>Chaque contact a<br /><em>une prochaine étape.</em></h2><p>Rassemblez les coordonnées, les notes et les étapes de vos prospects. Planifiez une relance ou une séance d’essai, puis créez le profil adhérent quand l’accompagnement commence.</p></div><ProductCapture view="crm" /><div className="vp-inline-facts"><span>Pipeline commercial</span><span>Notes & rappels de relance</span><span>Conversion prospect → adhérent</span></div></section>
      <section className="vp-section vp-split" id="suivi"><div><span className="marketing-kicker">03 · COACHING & SUIVI</span><h2>Le contexte de chacun.<br /><em>À chaque séance.</em></h2><p>Programmes, historique et échanges restent liés à l’adhérent. Consultez les séances réalisées, les performances et les mesures renseignées pour préparer la suite.</p><Link to="/solutions/coach-sportif" className="marketing-text-link">Découvrir Velatra Coach<ArrowRight size={17} /></Link></div><div className="vp-panel"><span className="marketing-kicker">L’ESPACE ADHÉRENT</span><h3>Le suivi continue entre deux séances.</h3><FeatureList items={['Consulter les programmes partagés par le coach', 'Enregistrer ses séances et suivre ses performances', 'Retrouver les plans et le suivi nutritionnel', 'Échanger avec son coach dans la messagerie', 'Consulter son espace depuis un ordinateur ou un mobile']} /><p className="vp-note">Velatra est une application web responsive. Les contenus disponibles dépendent de ce que le coach partage.</p></div></section>
      <section className="vp-section" id="programmation"><div className="vp-section-heading"><span className="marketing-kicker">04 · PROGRAMMATION</span><h2>Programmez à votre façon.</h2><p>Votre méthode reste au centre. L’IA Velatra vous aide à préparer et adapter vos propositions, puis vous les relisez, ajustez et validez.</p></div><div className="vp-two-col"><article className="vp-panel"><Dumbbell size={24} /><h3>Manuellement</h3><p>Composez vos programmes et séances à partir des exercices. Ajustez les séries, les répétitions et les consignes selon les objectifs de chaque adhérent.</p></article><article className="vp-panel vp-panel-tint"><Sparkles size={24} /><h3>Avec l’aide de l’IA Velatra</h3><p>Préparez une proposition de programme à partir du profil et des objectifs, puis reprenez-la dans l’éditeur. Le coach garde la décision finale.</p><span className="vp-note">L’assistance IA fait partie du produit. Aucun abonnement IA séparé.</span></article></div><p className="vp-note vp-ai-note">L’assistant conversationnel aide aussi à comprendre les séances et le programme. Il ne modifie pas seul les programmes de l’adhérent.</p><Link to="/tarifs#programmation-sur-mesure" className="marketing-text-link">Vous préférez déléguer la programmation ?<ArrowRight size={17} /></Link></section>
      <ProductClosing />
    </div>
  </div>;
}
export { FeaturesPage };
